### ISSUE TITLE
Support user LHAPDF workflow

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABClient#1170]
Eventually aim to support this

https://hypernews.cern.ch/HyperNews/CMS/get/generators/1036.html

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEWKUtilities#How_to_compile_link_run

Could be CRABServer or core, dunno. In any case, it looks like a minor tweak to the CMSSW setup and the ability to download files (via squid, I would hope) would allow us to run these jobs in an automated way.

**Comment by ericvaandering** [comment]
I think this is the LHE workflow. Closing

**Comment by AndresTanasijczuk** [comment]
Actually it is not LHE workflow. This issue is more like the recent thread "Using modified versions of external libraries on CRAB3" (https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/532.html).
Let me re-open until we understand if this is solved or not.
