### ISSUE TITLE
Investigate "multicrab" like functionality

### ISSUE THREAD

**Issue by drsm79** [dmwm/CRABClient#1947]
The ReqMgr has a script interface that allows for adding multiple requests in a single interaction. CRAB should be able to reuse this to provide "multicrab" like functionality. This needs to be confirmed, and if not the case an outline of necessary changes made.

**Comment by AndresTanasijczuk** [comment]
I just read this issue for the first time. IIUC, what was discussed here was the muticrab approach to run on different datasets using either same or different CMSSW config and eventually combining the outputs of the different tasks. If by combining the outputs it was meant to publish in the same dataset, then I think all of this is already implement and this issue could be closed. Does anyone objects to close this issue?

**Comment by mmascher** [comment]
Let's close this.
