### ISSUE TITLE
Providing the client as a lib

### ISSUE THREAD

**Issue by cinquo** [dmwm/CRABClient#1948]
{{{(from chat with Simon)}}} Client could be used by external tools (HammerCloud, multicrab, ...), similar to what is being now done by unit tests when testing single commands. So the client needs to provide a package with the needed libraries that can be accessed (eg: {{{from CRAB3.Commands import submit}}}). This could require to go through the code organization and refacture if needed.
Refers also to #1942.
(leaving without a milestone since it is not something to have very soon, and that should be addressed after integration feedbacks).

**Comment by belforte** [comment]
current library API does this
