### ISSUE TITLE
Adapt get-output to multiple files per job

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABClient#2729]
Along with 2728, modify client to retrieve multiple EDM outputs, histograms, and arbitrary files.

**Comment by AndresTanasijczuk** [comment]
The getoutput command retrieves all the of output files.
So, IIUC the issue, this is done already. @ericvaandering ?

**Comment by ericvaandering** [comment]
This was CRAB3 WMAgent I suppose or at best CRAB3 panda. So closing....
