### ISSUE TITLE
publication failure recovery procedure

### ISSUE THREAD

**Issue by hernand** [dmwm/CRABClient#4077]
See discussion in https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/1977/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/2/2/1/1/2/1/1/1/1.html

The client should be able to trigger publication retry

It should be possible to manually resubmit jobs for which DBS publication failed.

**Comment by AndresTanasijczuk** [comment]
With the new resubmission code, it will be possible to resubmit finished jobs.
We can keep this ticket for the implementation of a 'crab publish' command, which would trigger the publication of finished jobs that have failed the publication. Currently this is done "by hand" by operators.
