### ISSUE TITLE
Improve versatility of the lumiList parameter

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4081]
We should support also objects, not only files of URLs. See https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2001.html

**Comment by belforte** [comment]
this is likely down with new crab report big patch from Andres. Need to check

**Comment by belforte** [comment]
reference: #4522

**Comment by belforte** [comment]
I think we have all we need in this area
