### ISSUE TITLE
Use crabclient as a library

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4091]
This will help with features like multicrab.

I think this is mostly a documentation issue, right now you can already import each command and run it in a python script, for example:

```python
import logging
import sys
from CRABClient.Commands.status import status

def setLogger():
    logger = logging.getLogger()
    handler = logging.StreamHandler(sys.stdout)
    res = status(logging.getLogger())()
    formatter = logging.Formatter("%(asctime)s:%(levelname)s:%(module)s %(message)s")
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


setLogger()
res = status(logging.getLogger(),['--task','crab_test_10preprod78'])()

print res
```

Users can setup the logging module as they want, e.g. redirect the commands messages to a file or /dev/null (just rely on the commands responses), increase the verbosity (`logger.setLevel(logging.DEBUG)`) etc.

However we should make sure that:
1) each command return something to the user (tipically the json oject returned by the server). Right now the status return `None` for example.
2) returning something does not screw up the CRABClient (it should not, but...)

**Comment by mmascher** [comment]
Closing the issue, the CRAB library is out there now. I just need to fix some things in the twiki for the users

**Comment by qunox** [comment]
Awesome
