### ISSUE TITLE
Add CRAB3 SLC6 RPM in CVMFS

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4138]
From my email archive:

QUESTION:
Hello, I am trying to submit a crab 3 job from sl6 cmslpc machines.  I have two issues.

First, I want to test my job interactively.  So I log into an sl6 machine, do cmsenv in an sl6 release area, and cmsRun my config file.  This works, but if I source /cvmfs/cms.cern.ch/crab3/crab.csh before issuing cmsRun, I get the following error::
[...]

ANSWER
Hi,

right now we are kind of "cheating" with SLC6, and only deploying the
SLC5 version. Since the client RPM brings its own python which depends
on gcc, then this screws up the CMSSW environment. That's why you can
run cmsRun before sourcing the client, but not after.

Since I think the client RPM for SLC6 are ready (or I can talk to
Diego to get the lates one), let's decide what to do. My
proposal is that we ask Bockjoo to monitor also
http://cmsrep.cern.ch/cmssw/comp.pre/RPMS/slc6_amd64_gcc481/ in
addition to http://cmsrep.cern.ch/cmssw/comp.pre/RPMS/slc5_amd64_gcc461/

In case a new RPM for SLC6 appears, we also deploy it to cvmfs. Then
we modify crab3 source script, which instead of being just a symlink
to the init.(c)sh (*) created by apt, should be a proper script which
check the OS version and source the right RPM.

**Comment by belforte** [comment]
as far as we know everything is working in this area. If not, we'll open a new one.
