### ISSUE TITLE
crab checkconfig

### ISSUE THREAD

**Issue by qunox** [dmwm/CRABClient#4182]
There should be a validation check on the parameters given in the user crabconfig.

 Various config parameter check has already been implemented in many part of the client coding. Having them at one place will be better and easier to maintain. The pset parameters will be a bit harder to validate.

**Comment by belforte** [comment]
it is a good idea, but we are not anywhere close to "refactor code fo make it simplere, easier to read and to maintain"

**Comment by belforte** [comment]
@emaszs as you get your handling of the code base, please decide if this is a refactoring worth scheduing or something to drop from the list

**Comment by belforte** [comment]
current code is good enough
