### ISSUE TITLE
Support Run Dependent MC

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABClient#4190]
See https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/7678.html 

Just putting this here so it's not forgotten. At this point it's unclear to me whether this needs treatment like LHE generator, etc or anything at all. We'll need to pull in someone with knowledge on the CMSSW side to understand exactly how the PSet can be configured to do this

**Comment by belforte** [comment]
@vlimant can you propose to CMSSW to inclide this in fwk then ? Make a pull request ?
I am assigning to myself so that I remember to close when that's done !

**Comment by vlimant** [comment]
Was actually https://github.com/cms-sw/cmssw/pull/5310 you can close this

**Comment by belforte** [comment]
thanks
