### ISSUE TITLE
Misinformation between crab status and crab status long 

### ISSUE THREAD

**Issue by qunox** [dmwm/CRABClient#4198]
![untitled](https://cloud.githubusercontent.com/assets/5649627/3670688/f570d40e-1246-11e4-842a-7fb7c580de34.png)

In the first half it is shown that 2 task is in kill state why 8 is in cool of, while the second half show that all task is in cool off. There should not be any difference in the information of job state as both use the same source.

**Comment by AndresTanasijczuk** [comment]
From looking at the current code, printLong and printShort should now be consistent. Closing, and in case we see inconsistency again, we re-open the issue.
