### ISSUE TITLE
Getoutput did not retributive all file when using the --parallel option 

### ISSUE THREAD

**Issue by qunox** [dmwm/CRABClient#4209]
![untitled](https://cloud.githubusercontent.com/assets/5649627/3748213/64de2aca-17d9-11e4-9a3d-b11902351b44.png)

In the example above, getoutput should retrieve 7 files, but it only retrieve 5 files. Have to fix this, 

low priority as user don't usually use the --parallel option

**Comment by belforte** [comment]
I guess this was fixed in the meanwhile. If we get new error reports we'll open new issues.
