### ISSUE TITLE
"allowNonProductionCMSSW" config parameter does not really means that

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4219]
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2109/1.html

**Comment by AndresTanasijczuk** [comment]
Another parameter that we might want to rename. @belforte @ericvaandering Any suggestion? 

If  allowNonProductionCMSSW = False, the server will do https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTUserWorkflow.py#L166-193 which checks if the arch and cmssw release are among the list in https://cmssdt.cern.ch/SDT/cgi-bin/ReleasesXML?anytype=1
So, it doesn't check that the cmssw release is of type "Production". 
But does "allowNonProductionCMSSW" mean what @belforte wrote in https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2109/1.html , i.e. "possibly non available at sites" ?

**Comment by ericvaandering** [comment]
How about skipCMSSWVersionCheck? Is that generic enough but true?

**Comment by AndresTanasijczuk** [comment]
Sounds good to me.

**Comment by belforte** [comment]
This is true. But does not immediately convey the message that
you will looking for a release that is VERY unlikely to be available.

On 04/15/2015 06:57 PM, Eric Vaandering wrote:
> How about skipCMSSWVersionCheck? Is that generic enough but true?

maybe:

allowNonGloballyDistibutedCMSSW (= False by default)

long, but clear and anyhow should only be used in VERY special cases,
as Andres noted we basically accepts anything which is on CVMFS

**Comment by ericvaandering** [comment]
How about “allowUndistributedCMSSW”. shorter and firmer. In any case “distributed” should be spelled correctly. :-)



> On Apr 15, 2015, at 14:59, Stefano Belforte <notifications@github.com> wrote:
> 
> This is true. But does not immediately convey the message that
> you will looking for a release that is VERY unlikely to be available.
> 
> On 04/15/2015 06:57 PM, Eric Vaandering wrote:
> > How about skipCMSSWVersionCheck? Is that generic enough but true?
> 
> maybe:
> 
> allowNonGloballyDistibutedCMSSW (= False by default)
> 
> long, but clear and anyhow should only be used in VERY special cases,
> as Andres noted we basically accepts anything which is on CVMFS
> 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dmwm/CRABClient/issues/4219#issuecomment-93549442>.
> 




Eric W. Vaandering 
Computing Physics Developer
CMS Computing Development Lead

Scientific Computing Division
Fermi National Accelerator Laboratory
630 962 7260 office
www.fnal.gov <http://www.fnal.gov/>

**Comment by belforte** [comment]
Sounds good. I had considered allowNotDistributedCMSSW but was worried that may be confused
with Distributed like in "distributed computing". Undistributed gives me (at least)
no such idea. As spelling goes probably Non is not an English word either :-)

**Comment by ericvaandering** [comment]
un/non. To-mae-toe/to-mah-toe. But I think un is better in this case.
