### ISSUE TITLE
Client should be more intelligent about (my)proxy

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/CRABClient#4223]
With every command, the client checks with myproxy for the length of the current proxy. It should update the expiration time and current time to a cache file in $HOME and only check if the proxy is close to expiration or if it hasn't been checked in a while.

The issue is that (maybe due to latency), each crab command takes approximately 5 seconds from when the logs print "Checking credentials" to when it prints "Myproxy is valid", which dominates the 6 second command execution time of running a "crab status"

**Comment by belforte** [comment]
more on the same tune in this issue 
https://github.com/dmwm/CRABServer/issues/4068

but this is all client work. Let's merge

**Comment by belforte** [comment]
laundry list from the old CRABServer issue

 bbockelm commented on Nov 2, 2013

We check proxies a lot -

    We always see if we should delegate the DN to a new server.
    We look at voms proxy lifetime.
    We check the proxy in MyProxy.

I propose to only do this once every 5-10 minutes in the client. This way, folks who do more than one "crab status" won't be so frustrated.

 belforte commented 10 hours ago

two things could be done:
1. each crab command calls voms-* too many times
2. all those call are awfully verbose in crab.log (thiis is to change in WMCore I guess)
3. if we really need (but I guess we don't) we could cache voms-proxy-info output in the task work directory, but I believe it is not worth

**Comment by belforte** [comment]
while doing this review this old PR
https://github.com/dmwm/CRABClient/pull/4414

**Comment by belforte** [comment]
@PerilousApricot only 6 years !!
