### ISSUE TITLE
Strip spaces from lumi mask before encoding

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/CRABClient#4224]
While poking at the logs, the lumi mask appears to be encoded with spaces. Since spaces have to be urlencoded to be transmitted to the server, it makes the already big request size much larger. This is what it looks like afterwards:

&runs=208551&runs=208686&lumis=10%2C110&lumis=1%2C111&lumis=33&lumis=1%2C55&lumis=69%2C249&lumis=51%2C53%2C55%2C122%2C124%2C169&lumis=1%2C252&lumis=1%2C3&lumis=1%2C5%2C7%2C65%2C81%2C336%2C338%2C350%2C353%2C383&

**Comment by belforte** [comment]
AFAIU this is is a non-issue then
