### ISSUE TITLE
Status should have a --errorSummary option

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/CRABClient#4235]
If you have a large task (> 10k jobs), it would be nice to have an --errorSummary option that would print per row an error reason and then to the right the job IDs. I can browse through --long, but it's super super long.

**Comment by AndresTanasijczuk** [comment]
crab status --long is printing the exit codes now (when the exit code is not defined it prints "Unknown"). And one can sort by exit code. 
We also have the error summary in crab status saying how many jobs failed with a given exit code, but the list of jobids per exit code is not shown. 
Is enough with what we have now or do you think we should add the list of jobids per exit code explicitly in the error summary?

**Comment by mmascher** [comment]
IMHO that's enough. We can always open new issues if we get complaints.

**Comment by AndresTanasijczuk** [comment]
Ok, closing this issue then.
