### ISSUE TITLE
Use preprod REST interface and prod database

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4243]
Curently if we have small fixes to make to the REST interface, and you want them to be available for users we have to wait until the nex CMSWEB production release to make them available to users.

However using links like https://cmsweb-testbed.cern.ch/crabserver/prod (instead of https://cmsweb-testbed.cern.ch/crabserver/prod) it is possible to access the testbed code and the production database, allowing users to test fixes deployed on the testbed but on the tasks already submitted to prod.

**Comment by belforte** [comment]
@mmascher nice idea, but needs is little to none. Shall we say we never do it ?

**Comment by belforte** [comment]
In the end, there is no real need for this. So we will not do it.
