### ISSUE TITLE
make sure input dataset is on Disk

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4253]
see
https://github.com/dmwm/DAS/issues/4200#issuecomment-53450120

**Comment by AndresTanasijczuk** [comment]
@mmasher Isn't this already solved by your commit https://github.com/dmwm/CRABServer/commit/39ab0c4ea4102ab3696630925cd1990ed3677c18 (an further later improvements)?

**Comment by mmascher** [comment]
Yes, it was done long time ago
