### ISSUE TITLE
Allow to not collect EDM and TFileService automatically

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4298]
Currently EDM and TFileService output files are collected automatically. It is not uncommon that users produce outputs that they don't care about in the end. For example: https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/7812.html
Talking about that with @belforte, he suggested we introduce a new parameter in the configuration file, which will be by default False and so the user has to take care of putting in the already existing config parameter "outputFiles" the list of output files he wants to collect. If he sets instead the new parameter to True, then we automatically collect EDM and TFileService outputs (as it is done now). Or maybe we can have two parameters, one for EDM files and one for TFileService outputs.

**Comment by AndresTanasijczuk** [comment]
@nizamyusli is now working on this issue. Reading @ericvaandering comment I am not sure we agreed on what we want to do here. What we proposed originally (with @belforte ) was to have a parameter to disable the automatic addition of EDM and TFileService output files to the list of output files to be transferred. In that case it would be up to the user to give the list of output files that have to be collected, in the already existing "outputFiles" parameter.
Do we agree on this? 

If yes, can you propose a name for the new parameter? Notice that the user could disable the automatic addition of EDM and TFiles, but then still add some of them to the "outputFiles" list. So I don't think that "deleteOutputs" is an appropriate name for the new parameter.

**Comment by belforte** [comment]
I think we agree with Eric. I am trying to think of a good name. More later

**Comment by belforte** [comment]
IgnoreAutomaticOutputCollection which is False by default.
