### ISSUE TITLE
CRABAPI library: check if it works and provide a very basic documentation

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4301]
Needs to be done after https://github.com/dmwm/CRABClient/issues/4300

I would like to check if everything is in place (I had an exception last time I tried it)

@PerilousApricot

**Comment by AndresTanasijczuk** [comment]
@mmascher Should we close this issue?

**Comment by mmascher** [comment]
I would like to check the doc first

**Comment by AndresTanasijczuk** [comment]
I think this can be closed now. Marco?

**Comment by mmascher** [comment]
Yes, go ahead and close it!

On Mon, Jun 8, 2015 at 9:39 AM, Andres Tanasijczuk <notifications@github.com
