### ISSUE TITLE
voGroup option has no effect

### ISSUE THREAD

**Issue by bkargoll** [dmwm/CRABClient#4325]
In my crabConfig.py I have the following lines:  
    config.section_("User")
    config.User.voGroup = 'dcms'

This should correspond to the dcms group I specify when creating my proxy and worked fine in Crab2. Nonetheless, when calling any crab command, I always get a query about my VO group:  
    $ crab checkusername
    Proxy file /tmp/x509up_u36073 exists with VO group = 'dcms' and VO role = 'NULL', but you have specified to use VO group = '' and VO role = 'NULL'.
    Do you want to overwrite the proxy (Y/N)?

I can explicitly give
    --voGroup dcms
in the command line for each crab command, and then in works fine.

**Comment by AndresTanasijczuk** [comment]
Closing this issue, as we have decided to keep doing the check on the proxy VO group/role, but only for some commands (submit, checkwrite, grtlog, getoutput) and this was done in #4434
