### ISSUE TITLE
Error summary of successful jobs

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABClient#4328]
Transferring jobs should not be in Error summary while they are still on transfer
```
{"216": {"0": [0, "OK", {}]},"213": {"0": [0, "OK", {}]}, "133": {"0": [0, "OK", {}]}, "134": {"0": [0, "OK", {}]}, "95": {"0": [0, "OK", {}]}, "138": {"0": [0, "OK", {}]}, "25": {"0": [0, "OK", {}]}
```
During that time 95, 134, 216 was in Transferring mode. And error summary says that they failed.
```
Details:			failed         12.7% ( 55/434)
				finished        3.9% ( 17/434)
				running        32.9% (143/434)
				transferred    20.7% ( 90/434)
				transferring   29.7% (129/434)

Publication status:		idle           48.8% (212/434)
				finished        2.3% ( 10/434)
				unsubmitted    48.8% (212/434)

Output dataset:			/DoubleMuParked/jbalcas-HG1411_new-6-Skimming_dataset_lumi_based-L-T_O-T_P-T_IL-T-1416752856-bb695911428445ed11a1006c9940df69/USER
Output dataset url:		https://cmsweb.cern.ch/das/request?input=%2FDoubleMuParked%2Fjbalcas-HG1411_new-6-Skimming_dataset_lumi_based-L-T_O-T_P-T_IL-T-1416752856-bb695911428445ed11a1006c9940df69%2FUSER&instance=prod%%2Fphys03

Error summary:
48 jobs failed with exit code 0:
	OK
```

**Comment by AndresTanasijczuk** [comment]
I think you got confused by the fact of seeing that the jobs 95, 134, 216 appeared in the list you printed 
`{"216": {"0": [0, "OK", {}]},"213": {"0": [0, "OK", {}]}, "133": {"0": [0, "OK", {}]}, "134": {"0": [0, "OK", {}]}, "95": {"0": [0, "OK", {}]}, "138": {"0": [0, "OK", {}]}, "25": {"0": [0, "OK", {}]}`
which I assume was the content of the error_summary.json file. The error_summary.json file is created/updated at the end of each PostJob execution by reading all the existing job_fjr.<jobid>.<crabretry>.json files (which are created when the PostJob for jobid starts execution). So yes, the error_summary.json file contains the exit code and exit message of jobs that are in transferring, not only jobs in failed. But then the status filters to show only the failed jobs in the Error summary part. In the status output you pasted, I guess the 48 jobs that are in the Error summary must be a subset of the 55 that were in failed status. So if you say that 95, 134, 216 were in transferring, then they should not be included in the 48 jobs shown in the Error summary. My question would be why the Error summary was showing only 48 jobs and not 55... I will assume you didn't copy/paste the Error summary for the other 7 jobs...

**Comment by AndresTanasijczuk** [comment]
I am closing this issue, as I am 99% convinced about my previous explanation. Please re-open if you think otherwise.
