### ISSUE TITLE
crab checkwrite should only check on allowed paths

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4342]
Currently crab checkwrite allows to check write permission to any specified lfn path. But maybe there is no sense to check write permission into paths that later CRAB will not allow to stageout. Therefore, we should restrict crab checkwrite to only accepts lfn paths /store/user/username, /store/group/<groupname>[/<subgroupname>]*/username and /store/local.

**Comment by AndresTanasijczuk** [comment]
See the code in the server: https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTUserWorkflow.py#L54-83

**Comment by mmascher** [comment]
I don't like that the same code is replicated ("copied/pasted") in the server and in the client. I discussed with @AndresTanasijczuk how to share the code.

**Comment by nizamyusli** [comment]
I updated the pull request. This update need ServerUtilities.py from the CRABServer. https://github.com/dmwm/CRABServer/pull/4631
