### ISSUE TITLE
create API to retrieve all columns from the TaskDB

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4368]
One use case for which we need this: 
getcommand can get an empty list of files to retrieve. This can be because the user has set the transfer flag to False. But since currently the client has no way retrieve the value of the transfer flags from the TaskDB, it can not give a precise message to the user like "hey, you have set the transfer flag to False, so I can not retrieve any files" and instead is saying something like "having no files to retrieve is the normal behavior if you have set the transfer flag to False".

**Comment by AndresTanasijczuk** [comment]
@mmascher has implemented this in https://github.com/dmwm/CRABServer/commit/d614d1f60f4ac62f1714057e28477edc50b806f6
Closing the issue.

**Comment by mmascher** [comment]
If I remember correctly the idea was to use this API to check the transferoutput flag and improve some messages. But I believe that the messages are clear enough now. No need to hurry up with that
