### ISSUE TITLE
crab status --json failing

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4383]
I see this is failing. @AndresTanasijczuk do you confirm it?

**Comment by AndresTanasijczuk** [comment]
I get the same output for 'crab status --json' (in a task with 1 job) using the current client in cvmfs and the current master branch:

$ crab status -d crab_test --json
Warning: Incompatible CRABClient version "development" 
Server is saying that compatible versions are: ['3.3.8', '3.3.9.rc2', '3.3.9', '3.3.10', '3.3.9.pre2']
Task name:			150123_071602_crab3test-5:atanasi_crab_test
Task status:			COMPLETED
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150123_071602_crab3test-5%3Aatanasi_crab_test
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=atanasi&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150123_071602_crab3test-5%3Aatanasi_crab_test
Details:			finished      100.0% (1/1)

{'1': {'Retries': 0, 'WallDurations': [136.0], 'StartTimes': [1421997625.0], 'SubmitTimes': [1421997431.0], 'JobIds': ['324009.0'], 'EndTimes': [1421997761.0], 'Restarts': 0, 'RecordedSite': True, 'State': 'finished', 'ResidentSetSize': [44660], 'TotalUserCpuTimeHistory': [24], 'SiteHistory': ['T2_CH_CERN'], 'TotalSysCpuTimeHistory': [4]}}
Log file is /afs/cern.ch/work/a/atanasi/CRAB3-tutorial/CMSSW_7_0_5/src/crab_test/crab.log

**Comment by AndresTanasijczuk** [comment]
We checked this again with @nizamyusli doing crab status --json with and without --long, and there was no failure. We checked also the code and found nothing potentially wrong. Closing this issue; could be reopened if necessary.
