### ISSUE TITLE
crab getoutput/getlog not working with gfal-copy

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4385]
$ crab getoutput -d crab_test_getoutput_getlog
Setting the destination to /afs/cern.ch/work/a/atanasi/CRAB3-tutorial/CMSSW_7_0_5/src/crab_test_getoutput_getlog/results 
Retrieving 30 files
Placing file 'pooloutputmodule_4.root' in retrieval queue 
Retrieving pooloutputmodule_4.root 
Placing file 'tfileservice_4.root' in retrieval queue 
Retrieving tfileservice_4.root 
Placing file 'pooloutputmodule2_4.root' in retrieval queue 
Retrieving pooloutputmodule2_4.root 
Placing file 'pooloutputmodule_9.root' in retrieval queue 
Retrieving pooloutputmodule_9.root 
Placing file 'tfileservice_9.root' in retrieval queue 
Retrieving tfileservice_9.root 
Placing file 'pooloutputmodule2_9.root' in retrieval queue 
Retrieving pooloutputmodule2_9.root 
Placing file 'pooloutputmodule_6.root' in retrieval queue 
Retrieving pooloutputmodule_6.root 
Placing file 'tfileservice_6.root' in retrieval queue 
Retrieving tfileservice_6.root 
Placing file 'pooloutputmodule2_6.root' in retrieval queue 
Retrieving pooloutputmodule2_6.root 
Placing file 'pooloutputmodule_8.root' in retrieval queue 
Retrieving pooloutputmodule_8.root 
Placing file 'tfileservice_8.root' in retrieval queue 
Placing file 'pooloutputmodule2_8.root' in retrieval queue 
Placing file 'pooloutputmodule_5.root' in retrieval queue 
Placing file 'tfileservice_5.root' in retrieval queue 
Placing file 'pooloutputmodule2_5.root' in retrieval queue 
Placing file 'pooloutputmodule_3.root' in retrieval queue 
Placing file 'tfileservice_3.root' in retrieval queue 
Placing file 'pooloutputmodule2_3.root' in retrieval queue 
Placing file 'pooloutputmodule_2.root' in retrieval queue 
Placing file 'tfileservice_2.root' in retrieval queue 
Placing file 'pooloutputmodule2_2.root' in retrieval queue 
Placing file 'pooloutputmodule_7.root' in retrieval queue 
Placing file 'pooloutputmodule_10.root' in retrieval queue 
Placing file 'tfileservice_10.root' in retrieval queue 
Placing file 'tfileservice_7.root' in retrieval queue 
Placing file 'pooloutputmodule2_7.root' in retrieval queue 
Placing file 'pooloutputmodule2_10.root' in retrieval queue 
Placing file 'pooloutputmodule_1.root' in retrieval queue 
Placing file 'tfileservice_1.root' in retrieval queue 
Placing file 'pooloutputmodule2_1.root' in retrieval queue 
Please wait
Warning: Failed retrieving pooloutputmodule_6.root
Warning: Failed retrieving pooloutputmodule_8.root
Warning: Failed retrieving pooloutputmodule2_4.root
Warning: Failed retrieving pooloutputmodule_9.root
Warning: Failed retrieving pooloutputmodule2_6.root
Warning: Failed retrieving pooloutputmodule_4.root
Warning: Failed retrieving pooloutputmodule2_9.root
Warning: Failed retrieving tfileservice_4.root
Warning: Failed retrieving tfileservice_9.root
Warning: Failed retrieving tfileservice_6.root
No file retrieved

The crab.log file in /afs/cern.ch/user/a/atanasi/public/for_Justas/crab_test_getoutput_getlog

**Comment by juztas** [comment]
Hi @AndresTanasijczuk everything for me works for your task. Maybe you had problems in your environment, can you try again ? Did you did this on lxplus or on your private machine?

**Comment by AndresTanasijczuk** [comment]
On lxplus. And Federica got the same issue.

**Comment by juztas** [comment]
But if you try now it works ? In this case I would need your environment which you had (crab, cmssw), same lxplus machine and have you tried `crab -d getoutput`, it should print all command which were executed for transferring files.

**Comment by juztas** [comment]
And I remember you asked about which command is in use gfal or lcg, this one is printed only in crab checkwrite. I will add soon this in remote_copy.py

**Comment by AndresTanasijczuk** [comment]
It is still not working for me.
I put a file in /afs/cern.ch/user/a/atanasi/public/for_Justas/crab_debug_getoutput.txt with the output of crab --debug getoutput using the crab client crab_pre.sh.
I used lxplus0024

**Comment by AndresTanasijczuk** [comment]
I also put in /afs/cern.ch/user/a/atanasi/public/for_Justas/ 3 txt files with the output of 'env' before and after sourcing cmsenv and crab.

**Comment by juztas** [comment]
@AndresTanasijczuk I suspect only one thing, which might look strange, but can you test this step by step :
```
ssh lxplus0024
mkdir test_for_justas
cd test_for_justas
cmsrel CMSSW_7_0_5
cd CMSSW_7_0_5/src
cmsenv
source /cvmfs/cms.cern.ch/crab3/crab.sh
crab rmk --task=150126_160629_crab3test-3:atanasi_crab_test_getoutput_getlog
crab --debug getoutput crab_test_getoutput_getlog/
```
Let me know status and in case we can take a look tomorrow.

**Comment by AndresTanasijczuk** [comment]
Mine was an environment problem. I fixed this and now I can retrieve logs and outputs.
