### ISSUE TITLE
Improvements for crab status --dryrun

### ISSUE THREAD

**Issue by annawoodard** [dmwm/CRABClient#4406]
From @ericvaandering:
1) Do the math for the user and suggest the "correct" splitting to get to our recommended 8 hr jobs.
2) Much more difficult, but allow them to change the splitting in the config file and re-split the task (or I guess delete the current task and replace it transparently)

Also: implement warnings in the case of memory estimate exceeding normal envelope. Also: collect more data about how accurate the estimates are.

**Comment by mmascher** [comment]
For 2, maybe we can edit the splitting args in the oracle DB (and remove the dryrun flag), and the put the task status to `NEW` (instead of `RESUBMITTED`)

**Comment by annawoodard** [comment]
Additional items from @mmascher that can be included in this ticket:

Instead of parsing the dagman input file inside getDryRunOpts, I would like to take the information we need from the task database and/or from some adhoc json file we upload from the TW.

**Comment by mmascher** [comment]
I did a basic testing and it seems to work pretty good! I have one other request for you: here in the TW (*) you are running alternatively the dryrun or the dagman submission, depending on the dryrun flag. do you see anything wrong to change the logic to something like:

```python
handler.addWork( DryRunUploader(config=config, server=server, resturi=resturi, procnum=procnum) )
if task['tm_dry_run'] == 'F':
    handler.addWork( DagmanSubmitter(config=config, server=server, resturi=resturi, procnum=procnum) )
```

meaning we upload the "dryrun sandbox" no matter what, and submit to dagman submitter only if we are not in the "dryrun" mode.

The advantage is that we can add a crab command that runs the "verification code" a-posteriori. Where I am going with it is that if operators could run the dryrun verification code on user's tasks it would be great imho (we can check it the estimation works on users task!)

It should not be a big change, do you think you can work on thet this/next week?

(*)
https://github.com/dmwm/CRABServer/commit/36aa8c4c78500036de7fcad4092eb4a8cc5b8fea#diff-ff551d45cfbad36f9969f573a4176a2dL142

**Comment by mmascher** [comment]
Actually, a possibility is that the `crab submit --dryrun` run only until `Task consists of 5 jobs to process 10 lumis` (*) and the other command does the verification (it saves some time to people only interested in the splitting parameter.. well, maybe people can just hit CTRL-C in that case, but we have to print a message about that.. I don't know :))

(*)
```
[mmascher@lxplus0163 wf]$ crab submit --dryrun
Will use configuration file crabConfig.py.
Sending the request to the server
Success: Your task has been delivered to the CRAB3 server.
Waiting for task to be processed
Checking task status
Task status: NEW
Please wait...
Task status: UPLOADED
Please check crab.log

Creating temporary directory for local test run (needed for timing estimates) in /tmp/mmascher/tmpTEO9FW
Executing test, please wait...
Using LumiBased splitting

Task consists of 5 jobs to process 10 lumis
The estimated memory requirement is 607 MB
The longest job will process 2 lumis, with an estimated processing time of 3 minutes
The average job will process 2 lumis, with an estimated processing time of 3 minutes
The shortest job will process 2 lumis, with an estimated processing time of 3 minutes

Dry run requested: task paused
To continue processing, use 'crab proceed'

Log file is /afs/cern.ch/user/m/mmascher/wf/crab_testecmmascher-dev6_63/crab.log
```

**Comment by annawoodard** [comment]
> It should not be a big change, do you think you can work on thet this/next week?

Sure.

> Actually, a possibility is that the crab submit --dryrun run only until Task consists of 5 jobs to process 10 lumis (*) and the other command does the verification (it saves some time to people only interested in the splitting parameter.. well, maybe people can just hit CTRL-C in that case, but we have to print a message about that.. I don't know, I am just thinking out loud :))

I'd vote for keeping the functionality separate, because it seems like the estimation fits with the questions you are asking when you run dryrun ("What is my splitting configuration? Is it correct?"). I could give an exit path for the user-- "Your task consists of X jobs to process Y lumis. Would you like to estimate the processing time? [y/n]"
