### ISSUE TITLE
Missing printouts in the crab getlog

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4416]
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/463/1/1/1.html

**Comment by mmascher** [comment]
Example of printout I did not find in the log: https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/remote_copy.py#L229

**Comment by AndresTanasijczuk** [comment]
@mmascher You have fixed this in https://github.com/dmwm/CRABClient/pull/4560 right?

**Comment by mmascher** [comment]
yes, I did
