### ISSUE TITLE
crabCommand should be quiet

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABClient#4418]
Writing my first multiCRAB program I see that all the normal output from crab status, etc is printed to stdout. It should, IMO, be quiet by default and if needed a flag can be added to get that output. I'm parsing the JSON results of the commands and want my own printouts unmolested.

**Comment by AndresTanasijczuk** [comment]
As suggested by @mmascher I documented in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRABClientLibraryAPI#Multicrab_using_the_crabCommand that user can do getLoggers(60) if he want crabCommand to be quiet.
Should we close this issue?

**Comment by AndresTanasijczuk** [comment]
@mmascher are you satisfied with the documentation? 
@ericvaandering are you ok with Marco's proposal?

**Comment by ericvaandering** [comment]
GetLoggers(60) seems like some black magic incantation. 

I suspect "60" is some magic threshold that silences most (all) messages, but it seems to me a) the function name is misleading and b) I should be able to import a constant and set that so something more like

from .... import setLogLevel, noLogInfo

setLogLevel(noLogInfo)

**Comment by AndresTanasijczuk** [comment]
Ok @ericvaandering 
This aligns more with what was proposed originally in https://github.com/nizamyusli/CRABClient/commit/fdbb0701df3b57818c9b128a66dd723b73f81184

**Comment by mmascher** [comment]
Hi Eric,

yes, logging.DEBUG is 10, logging.INFO=20 and so on. 60 is a value above
logging.CRITICAL (50) that silence everything. I agree to use something
more "userfriendly", a constant noLogInfo should do it.

Cheers,

Marco
