### ISSUE TITLE
Add a warning if LHE files have absolute path (?)

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4431]
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/483/1/1/1/1.html

As said in the forum, I am actually not sure that we really need to do that, opening a ticket so we can discuss this. Eventually we might close the ticket and leave things as they are.

**Comment by AndresTanasijczuk** [comment]
But absolute paths are valid in general. In https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/483/1/1/1/1.html the user was giving the wrong path (he was giving the path to the local file I think), wasn't it?

**Comment by belforte** [comment]
unfortunately now absolute paths work if they point to CVMFS, so I think we do not go into details and stick with current situation that when jobs fail because of this we slap users fingers
