### ISSUE TITLE
Better name for outLFN configuration parameter ?

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4438]
outLFN may lead to think that a full LFN has to be given, like /store/user/atanasi/myfile.root
There were users doing that. CRAB does not fail. The files will be saved in /store/user/atanasi/myfile.root/\<primary-dataset\>/\<publish-dataname\>/\<time-stamp\>/0000/\<real-out-file-name\>.root

**Comment by AndresTanasijczuk** [comment]
Also the --lfn option in crab checkwrite could be changed.

**Comment by AndresTanasijczuk** [comment]
@belforte  Any suggestion of a better name?  
I thought about "outputDirectory"/"outputDir"/"outputPath", "storageDirectory"/"storageDir"/"storagePath" or "storeDirectory"/"storeDir"/"storePath".
For the storage site, the parameter is called "storageSite".

**Comment by ericvaandering** [comment]
I think I prefer storagePath to harmonize between the two. But do we need to include "logical" somehow so that people are not putting in physical paths? Perhaps not.

**Comment by belforte** [comment]
all nice names, but in order to pick one:
assuming  config.parToBeNamed=string
where exactly will data be written ?
/store/user/belforte/<string>/<primary-dataset>/<publish-dataname>/<time-stamp>/0000/<real-out-file-name>.root
?

**Comment by belforte** [comment]
i need to learn how to use angular brackes in here. sorry for confused posting

**Comment by belforte** [comment]
trying again:
assuming the param to be named has the value "STRING". Will data be written here ?
```
 /store/user/atanasi/STRING/<primary-dataset>/<publish-dataname>/<time-stamp>/0000/<real-out-file-name>.root
```
and by the way where `<real-out-file-name>` comes from ? And is file type forced to be `.root` ?

**Comment by AndresTanasijczuk** [comment]
No, it will be written to `STRING/\primary-dataset\>/\<publish-dataname\>/\<time-stamp\>/0000/\<real-out-file-name\>.root
\<real-out-file-name\> comes from the pset if CRAB recognizes the output file automatically (if it is EDM or TFIle) or from what the user provides in the "outputFiles" parameter.

**Comment by AndresTanasijczuk** [comment]
But STRING is checked to be either /store/user/\<username\>, /store/group/\<something\> or /store/local/\<something\>

**Comment by belforte** [comment]
so `<real-out-file-name> ` should already include `.root` , right ?

As to the name then, what about: LFNPath ?
I would make an effort to avoid LFN/PFN confusion here (we had enough of /store/caf and storagePath in Crab2)

 And make it clear the notes you wrote before about how it is used in bulding the LFN.

**Comment by AndresTanasijczuk** [comment]
Yes, `\<real-out-file-name\>` should already contain the file extension.

The confusion I always have with "path" is if it refers only to the directory or includes also the `\<real-out-file-name\>`. In that respect, wouldn't "LFNDirPath" be better?

**Comment by AndresTanasijczuk** [comment]
I think documentation is already clear (I just fixed a few links that were outdated), but if you think it should be improved, let me know:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile (see outLFN parameter)
https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3DataHandling (the part about output file names should be ok, the other sections about publication dataset should still be improved)

**Comment by belforte** [comment]
in my understanding path is a directory.
What about  LFNDirPrefix  ?

**Comment by AndresTanasijczuk** [comment]
That may be better. And don't we want to keep in the name something that makes clear that this is for output files? So what about "outLFNDirPrefix" ?

**Comment by belforte** [comment]
yes we do want to have "out" in the name. Maybe less uppercase ? "outLfnDirPrefix"

**Comment by AndresTanasijczuk** [comment]
But we have already decided some time ago and we use the convention that acronyms go all in uppercase: inputDBS, publishDBS, allowNonProductionCMSSW (or its renaming allowUndistributedCMSSW), maxMemoryMB, ASOURL, extraJDL. And we had already "outLfn" and we renamed it to "outLFN".

**Comment by annawoodard** [comment]
I would vote to leave out 'prefix.' I think the meaning might be a little confusing for some people, because it's usually used in the context of words and not directory structures. Maybe just outLFNDir? Or, if you want to keep the idea of it being the top level, outLFNDirBase, or outLFNDirRoot?

**Comment by belforte** [comment]
outLFNDirBase is good for me.

**Comment by AndresTanasijczuk** [comment]
Ok, decision made for "outLFNDirBase". Thanks to all for contributing.
