### ISSUE TITLE
Add --wait option in crab resubmit

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4453]
'crab resubmit --wait' should check the task status in the way same as 'crab submit --wait' does (wait until the task status becomes SUBMITTED -or FAILED or UNKNOWN-). We should reuse checkStatusLoop from submit command.

**Comment by mmascher** [comment]
Lets pur it in client utilities
Il 17/apr/2015 15:01 "Andres Tanasijczuk" <notifications@github.com> ha
scritto:
