### ISSUE TITLE
Change error messages for wrong project directories

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4454]
See  https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/541/2.html

From private emails with @belforte :

Maybe
 if not a file: print directory .. does not exits
 if not a directory or something wrong (missing .requestcache ?)
  print : not a valid crab project directory
 then check for common problems (missing .requestcache, ends with .py
 starts with #!/ , lacks permissions... whatever) and print more

Indeed whenever we write things like "can't find .requestcache"
is a message for us, not for the user, we can surely print
one message for the user and one for us, but the one for the
user should come first.
I also do not like hidden files, but this may be a personal taste,
for sure if we create a hidden file we should not expose it
to the user elsewhere like if he could check before running !

**Comment by AndresTanasijczuk** [comment]
Closing as it has been fixed in #4464
