### ISSUE TITLE
Optimize error summary in status report for jobs with same exit code but different error message

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4457]
It is common to have jobs with same exit code but different error message in two situations:
1) The failure occurred in the post-job
2) The error message contains a file name
What the code does now:
For each exit code
- make subgroups of jobs grouping by error message
- sort by most frequent error message
- print the first 3 more frequent error messages

This may be too much printing in case of the error messages just differ in a file name.
We may introduce an option (--errorsummary) that if not given we just print a short version of the error summary (maybe without error messages, just exit codes), and if given we print a more detailed error summary. Propositions are welcome.

**Comment by annawoodard** [comment]
'Errorsummary' to me sounds like the inverse: if the user gives it, they want the shorter version (just exit codes), and if they omit it, they want the detailed version. If you want the short version to be default, consider changing the option to 'verboseErrors' or 'longErrors.' In any case I vote that the detailed version be default. We should assume many users will not inspect the options carefully. So these users will always get the default, and I'd say they have much more to gain by seeing the messages explicitly.

**Comment by mmascher** [comment]
With a recent fix from Andres the verbose is really verbose now. I vote for the summarized to be the default with explicitly printing `Please use --verboseErrors` for the details about the errors (or something like that)
