### ISSUE TITLE
crab task command should sort tasknames

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4468]
@juztas reported this:

crab tasks --instance=preprod
....
\--------------------------------------------------------------------------------
150408_145305:jbalcas_crab_835condor_load_memory602570
                                SUBMITTED
\--------------------------------------------------------------------------------
150408_145322:jbalcas_crab_835condor_load_memory139676
                                SUBMITTED
\--------------------------------------------------------------------------------
150408_145333:jbalcas_crab_835condor_load_memory924247
                                SUBMITTED
\--------------------------------------------------------------------------------
150408_145345:jbalcas_crab_835condor_load_memory937888
                                SUBMITTED
\--------------------------------------------------------------------------------
150408_145442:jbalcas_crab_835condor_load_memory1246950
                                SUBMITTED
\--------------------------------------------------------------------------------
150324_095219:jbalcas_crab_HG1504a-2-MinBias_PrivateMC_EventBased-L-T_O-T_P-T_IL-F-dryRun
                                UPLOADED
\--------------------------------------------------------------------------------
150401_064607:jbalcas_crab_HG1504a-2-Analysis_LumiBased_on_Data-1
                                UPLOADED
\--------------------------------------------------------------------------------

**Comment by juztas** [comment]
it is lowest priority :)
