### ISSUE TITLE
make crab.sh to explicitely use bash

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4470]
put #!/bin/bash at top of crab.sh setup script, forcing execution in bash rather then e.g. zsh

should hopefully fix
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/386/1/1/1/1/1/1/1/1.html
and
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/563.html

this was also briefly touched in another issue #4391 but it is not clear in that if there is intention to add the shebang or not

**Comment by AndresTanasijczuk** [comment]
@mmascher can you add this in your new crab scripts ?

**Comment by belforte** [comment]
the latest init script crab_light.sh starts indeed with =#!/usr/bin/env bash=
