### ISSUE TITLE
New conflict between CRAB and CMSSW

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABClient#4474]
See https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3486.html for details

**Comment by AndresTanasijczuk** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/572.html

**Comment by belforte** [comment]
should be solved by current `crab_env_bootstrap` https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#crab_env_bootstrap_sh_script_to
