### ISSUE TITLE
OpenSSL packaged incorrectly

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/CRABClient#4485]
Seen from crab.log on 3.3.16 from CVMFS:

```
DEBUG 2015-05-19 11:52:53,737:   Executing :                                       
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout                 
 output : subject= /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=meloam/CN=692113/CN=Andrew Malone Melo
                                                                                   
 error: WARNING: can't open config file: /build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/tmp/BUILDROOT/779a792f862039a4ebba572299ebbb36/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/slc6_amd64_gcc481/external/openssl/1.0.1m-comp/ssl/openssl.cnf
```

**Comment by mmascher** [comment]
not sure where this is coming from

**Comment by PerilousApricot** [comment]
From crab.log with the latest client

**Comment by mmascher** [comment]
Yeah, I mean why this error is shown, I need to debug :)

**Comment by PerilousApricot** [comment]
Oh, gotcha :)

**Comment by juztas** [comment]
During RPM build it points to this location 'build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/tmp/BUILDROOT/779a792f862039a4ebba572299ebbb36/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/slc6_amd64_gcc481/external/openssl/1.0.1m-comp/ssl/openssl.cnf' which does not exist, when client is deployed anywhere. Newer RPM creation tool does not ignore these warnings and suggests to fix it. 

@geneguvo @BrunoCoimbra can you take a look?

**Comment by belforte** [comment]
let's live with this

**Comment by davidlt** [comment]
Looking at your `openssl.spec` you don't have a proper `--openssldir`, by default it is `%{i}/ssl`. Note, this also means that your OpenSSL probably is not able to verify SSL connections (e.g. to cmsweb.cern.ch). I also see that you don't use `no-asm`, but then you might build a broken OpenSSL package if you end on AVX/AVX2/AVX512/etc machine. Remember, we have 10-years worth of CPUs in WLCG. E.g. my CERN desktop has 8 year old CPU, anything above SSE is out of question.

**Comment by belforte** [comment]
so maybe we can fix it... but this is beyond me. Assigning to @mmascher 
by the way.. thanks @davidlt  but.. care to share your real name  ?

**Comment by davidlt** [comment]
```
% phonebook -a davidlt | grep 'Display Name:'
Display Name:       David Abdurachmanov
```

**Comment by geneguvo** [comment]
Hi,
Please be extremely careful when doing changes for openssl in the comp stack. We had serious performance problems with the no-asm option when moving to modern openssl versions and crypto algorithms, so we cannot use it. We also never had any report of having it broken because of asm. This was probably an issue with the older (ancient) versions.

For the openssldir, we can (should) definitely set it to something more reasonable like /etc/grid-security/certificates or /etc/pki/tls, but there's no guarantee that would always be the right place. On our applications, that has always been a configuration we override (capath, cacertpath, etc), and crabclients should do  the same regardless of default.

Cheers,
Diego.

**Comment by davidlt** [comment]
Actually what we should check is that `no-asm` does not generate, e.g. AVX instructions on newer machines (e.g, Haswell Xeon).

`/etc/pki/tls` is a good option as that's there CERN installs their certificates and it's also the official place according to RHEL.
```
$ repoquery -l CERN-CA-certs
[snip]
/etc/pki/tls/certs/CERN-bundle.crt
/etc/pki/tls/certs/CERN-bundle.pem
/etc/pki/tls/certs/CERN_Certification_Authority.crt
/etc/pki/tls/certs/CERN_Certification_Authority.pem
/etc/pki/tls/certs/CERN_Certification_Authority.signing_policy
/etc/pki/tls/certs/CERN_Grid_Certification_Authority.crt
/etc/pki/tls/certs/CERN_Grid_Certification_Authority.pem
/etc/pki/tls/certs/CERN_Grid_Certification_Authority.signing_policy
/etc/pki/tls/certs/CERN_Root_CA.crt
/etc/pki/tls/certs/CERN_Root_CA.pem
[snip]
```

**Comment by belforte** [comment]
on the good side:
1. we are moving (next months or so) to a light version of CRAB Client
    which can live withing CMSSW environment, and will not try to distribue OpenSSL with CRAB.
    So we should be using whatever David packages
2. CRAB server lives in COMP environmnet and should be using whatever Diego packages (IIUC)

it that were all, I'd say, the two of you sort it out, and do not bother the effort of making 
someone like me understand :-)

Of course we'll need CMSSW to keep having good up to date OpenSSL,pycurl & C., in
all supported releases, possibly backporting fixes etc., but talking with Eric
we assumed that's the case.

We are left with the possibility that someone still wants to install current full, heavy weigth
CRAB client. I do not now the use case for that, but in our large world it is difficult to be sure
that something is not used/needed until you remove it and wait for complains.
So... imagining we do 1. but do not deprecate current client for a while, is there still
something we should worry about withing Crab (i.e. for Marco to do :_) ), or can we close
this issue in the scope of CRAB ?

**Comment by belforte** [comment]
After reviewing. Closing, since it is not a CRAB issue. Proper OpenSSL is in interesting problem, but for CMSSW where it is needed also for DAS, DBS etc. not worth having a parallel thread in here.
