### ISSUE TITLE
properly handle shortcuts in command line autocompletion

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4492]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/616.html
quoting from that posting:

 It's very nice that crab supports tab completion for its subcommands. The only thing is that the shorthands (e.g. chk, log, out, ...) seem not be included. This is not a problem by itself, but when using one of the shorthands, the tab completion is not handed back to the shell for completion of foldernames.

**Comment by AndresTanasijczuk** [comment]
I think this was fixed by Matthias in https://github.com/dmwm/CRABClient/pull/4484
@matz-e Can you confirm?

**Comment by matz-e** [comment]
Yes, should be fixed in there.  Subcommands still have to be fully typed in by hand, though, only long commands are completed.  After typing the subcommand, long or short, tab completion should work as normal.

**Comment by mmascher** [comment]
great, thanks Matthias. I'll need to figure out how to include the autocompletion script in the CMSSW environment once the work about COMP and CMSSW separation has been completed.

**Comment by AndresTanasijczuk** [comment]
Hi @matz-e 
You said that "after typing the subcommand, long or short, tab completion should work as normal." But I just tried the current master branch, and when I do 'crab <short-command>' and hit TAB, I get the list of crab commands (in long format only). So tab completion is not handed back to the shell for completion of foldernames until a crab command is given in long format.

```
$ crab st <TAB>
checkusername  getlog         help           proceed        remake         resubmit       submit         uploadlog      
checkwrite     getoutput      kill           purge          report         status         tasks
```

**Comment by matz-e** [comment]
Are you using the most up-to-date version?  You should source the bash completion in `src/`, otherwise you get the outdated version in CVMFS, I think.

**Comment by AndresTanasijczuk** [comment]
ok, sorry, it woks.
And what do you think about the short commands? Should they also be completed?

**Comment by matz-e** [comment]
Not really, IMO.  They are so short that one should actually be able to type them in without any completion help.

I never use them (I just type `st<TAB>`, for example, or search in my bash history), and I wouldn't cry a single tear if they would disappear.

**Comment by belforte** [comment]
indeed having autocompletion may make shortcuts useless.

**Comment by AndresTanasijczuk** [comment]
I personally don't even like to have the short command names.

**Comment by belforte** [comment]
anybody around who likes them ?

**Comment by AndresTanasijczuk** [comment]
Closing this issue then. Eventually removing shortcuts would be another issue.
