### ISSUE TITLE
avoid multiple CMSSW config imports when using CRAB CLIENT API

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4493]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/461/1.html
and
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/622/1/1/2/1/1.html

**Comment by AndresTanasijczuk** [comment]
and https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/665.html

**Comment by belforte** [comment]
this was already in https://github.com/dmwm/CRABClient/issues/4248

**Comment by belforte** [comment]
I believe that it will be solved once the plan outlined here is implemented
https://github.com/dmwm/CRABClient/pull/4824#issuecomment-528646511
