### ISSUE TITLE
add biglib to input tarball

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4494]
when tarring up user scram project subdir, in addition to
'lib', 'module', 'python' and all 'src/*/data' with any amount of /*
include also 'biglib'
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/601/1/1/1/2/1/2/1.html

**Comment by belforte** [comment]
@mmascher  this is very urgent since user tasks are failing now and there is no workaround. Should also be simple to do. Can you patch client now w/o waiting fro June's release ?

**Comment by mmascher** [comment]
Sure, will do it now

**Comment by mmascher** [comment]
Pull request done. now I need that one of @juztas or @geneguvo merge it. I don't have persmission. Diego is having lunch and Justas will probably wake up soon in the US

**Comment by mmascher** [comment]
FYI I cherry-picked this single commit on top of 3.3.16 and created a tag

**Comment by geneguvo** [comment]
I'll push it in the next few minutes. Just finishing a test...

**Comment by geneguvo** [comment]
DONE.

**Comment by mmascher** [comment]
Thanks Diego! Now waiting for the cvmfs deployment.

```
cat /cvmfs/cms.cern.ch/crab3/crab.sh
if [ -f /cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16/etc/profile.d/dependencies-setup.sh ]; ...
```

**Comment by geneguvo** [comment]
The build-agent just finished buildind/uploading it:
http://cmsrep.cern.ch/cmssw/comp.pre/RPMS/slc6_amd64_gcc481/cms+crabclient+3.3.16.patch1-1-1.slc6_amd64_gcc481.rpm
