### ISSUE TITLE
include user header files from scram directory in tarball for ROOT6

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4497]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/652/1/2/1/1/1/2/1/2/1/1/1/2.html

quoting from there:

For the problem with ROOT6 requiring user code header files, it should
be sufficient to add all the "interface" directories in src, identical
to what is done now for all the "data" directories.

this requires a change in
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/JobType/UserTarball.py

**Comment by AndresTanasijczuk** [comment]
Seems this is quite urgent. Should I make a pull?

**Comment by belforte** [comment]
feel free. I am also trying to do it, mostly as an exercise.
I am sure you will do it faster. I am curious if we end up with same code :-)

**Comment by mmascher** [comment]
@geneguvo , can you notify when you have merged https://github.com/cms-sw/cmsdist/pull/1603 please?

**Comment by juztas** [comment]
@mmascher I already merged after it got :+1:
