### ISSUE TITLE
CMSSW_cfg.py in inputs/ has wrong pkl filename

### ISSUE THREAD

**Issue by jordantucker** [dmwm/CRABClient#4501]
If I try to go into crab_working_dir/inputs and try to look at the config interactively, there's a problem:
```
% python -i CMSSW_cfg.py
Traceback (most recent call last):
  File "CMSSW_cfg.py", line 3, in <module>
    process = pickle.load(open('PSet.pkl', 'rb'))
IOError: [Errno 2] No such file or directory: 'PSet.pkl'
```

CMSSW_cfg.pkl is in there, though, so this is just a matter of choosing to fix either the filename or the CMSSW_cfg.py.

**Comment by AndresTanasijczuk** [comment]
The reason of
```
process = pickle.load(open('PSet.pkl', 'rb'))
```
is because in the WN the files are named PSet.py and PSet.pkl.
So we may want to call them the same way in crab_working_dir/inputs.
