### ISSUE TITLE
Remove short command names or not

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4503]
Should we remove the short command names? We currently have "st" (for "status"), "sub" (for "submit"), "out" and "output" (for "getoutput"), "log" (for "getlog"), "rep" (for "report"), "rmk" (for "remake"), "chk" (for "checkwrite"), "uplog" (for "uploadlog").

**Comment by AndresTanasijczuk** [comment]
Motivation for removing them started in https://github.com/dmwm/CRABClient/issues/4492

**Comment by mmascher** [comment]
For what it worth I vote for keeping the shortnames :)

**Comment by AndresTanasijczuk** [comment]
If Marco likes them, lets keep them :) Closing.
