### ISSUE TITLE
Prints in user PSet are redirected to crab.log.

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4505]
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/680/1/1/2/1/1/1/1/1/1/1/1/1/1/1.html

sys.stdout is redirected to logfile in https://github.com/dmwm/CRABClient/blob/3.3.1506/src/python/CRABClient/JobType/CMSSWConfig.py#L58-59

**Comment by belforte** [comment]
After reviewing the issue, I think that we should not "fix" this.
Users should not give to CRAB a pset which makes questions. And CRAB output need to stay terse, so it is OK that people find the output from their pset in crab.log

We do no support "interactive pset's". Period. And given that this is very rare, let's not worry now about making it more visible to users then via hanging.
