### ISSUE TITLE
Dry run should handle splitting configurations which result in long input file lists.

### ISSUE THREAD

**Issue by annawoodard** [dmwm/CRABClient#4515]
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/757.html.

If the user’s initial splitting parameters guess is very very wrong, the input file list may be longer than dryrun can pass to CMSRunAnalysis.sh with subprocess. We should truncate the list (we're only running over a small number of events, anyways.) This ties into improving the way we parse the dag file (see #4406.)

**Comment by mmascher** [comment]
Maybe as suggested by @juztas  we could write the list of files in a tarball file https://github.com/dmwm/CRABServer/issues/4872 ?

**Comment by annawoodard** [comment]
Yes, I think that's the way to go.
