### ISSUE TITLE
Fixes for crab report lumi files

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4522]
Issue started with this HN: https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/773.html

Discussed in CRAB3 meeting and agreed on the following points:
1) Make crab report work for LumiBased splitting first. Then work on the case of FileBased splitting (in particular input files not in DBS) where crab report should show info about processed/not-processed files instead of lumis.
2) The missing lumis file should be: input lumis AND lumi-mask AND run-range - processed lumis. Another possibility would be to use the lumis corresponding to failed jobs. This is important in case one wants to submit a recovery task before the original task finishes processing (e.g. because crab kill doesn't work and don't want to wait for tails of jobs to finish).

Proposal: crab report should return lumi files for:
a) The input dataset (from DBS, no matter of --dbs option; take the lumis from the data discovery step).
b) The processed lumis in the jobs that finished successfully (including transfer, but not necessarily publication, since publication can anyway be resubmitted -by an operator-). This should be taken from the lumis in input files as written in the FJR, as currently done when --dbs='no'.
c) The non processed lumis = input AND lumi-mask AND run-range - processed = a) AND lumi-mask AND run-range - b)
d) The lumis in the published output datasets (one file for each published dataset).
e) The duplicate lumis in the output. We don't need to use DBS; it is enough to look for duplicate lumis in b).
f) The duplicate lumis in the input, i.e. duplicate lumis in a) ? Even if CRAB can deal with them, it would be good to give this to users IMHO in case they were not expecting it. Especially for USER datasets.

**Comment by ericvaandering** [comment]
To point 1) if the input files contain lumi information, we should report it. People will still want to take that file and calculate the luminosity of their analysis. Of course, you can't tell what is "missing" in this case.

**Comment by AndresTanasijczuk** [comment]
@belforte I thought we have agreed on this issue, but seems we didn't. For example, we don't want to do a) and f) right?
About
c) The non processed lumis = input AND lumi-mask AND run-range - processed
It should actually be 
c) The non processed lumis = input AND lumi-mask AND run-range AND totalUnits cut - processed,
right? I.e. what CRAB was asked to process - what it finished processing. And we should not construct (input AND lumi-mask AND run-range AND totalUnits cut) ourselves, but take it from the files in run_and_lumis.tar.gz file, right?

**Comment by belforte** [comment]
depends what you mean by "we". I am sure I would never do a), but if someone wants to do it, it is easy, does not complicate code... feel free.
Indeed I similarly believe that f) is quite possibly never useful, but ... feel free.
You are correct about c): list of what to process is in run_and_lumis.tar.gz and that's all.
One may argue that in the end the only thing that matters is the list of correctly processed lumis, but somehow having also the input request one gets an idea of the % of completion.

**Comment by mmascher** [comment]
What about adding also `--recovery=1,3-7` ? That's for cases where things go terribly wrong and job are stuck in a certain state and you want to revcover only those jobs. Just an idea, it should be easy now with this review of the report command.

**Comment by AndresTanasijczuk** [comment]
Sounds a good idea to me.

**Comment by belforte** [comment]
+1
