### ISSUE TITLE
Use --checksum for get*

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/CRABClient#4523]
Many (most?) sites support checksumming on their SRM endpoint. Enabling checksums on get* would help prevent corrupt transfers

**Comment by juztas** [comment]
Partially fixed here: https://github.com/dmwm/CRABClient/pull/4518
Next step would be to check what checksum value is in CS DB

**Comment by juztas** [comment]
@PerilousApricot seems most sites with hadoop does not support that, which is bad

**Comment by AndresTanasijczuk** [comment]
Wasn't this issue fixed in 3.3.1510 ?

**Comment by juztas** [comment]
yes, done
