### ISSUE TITLE
crab status should print the schedd host name

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4524]
helps a lot for troubleshooting
(  @mmascher  assign to me)

**Comment by mmascher** [comment]
About this:

```
[mmascher@lxplus0085 wf]$ crab.sh st
CRAB project directory:		/afs/cern.ch/user/m/mmascher/wf/crab_test_1509rc1mmascher-dev6_0
Task name:			150803_144639:mmascher_crab_test_1509rc1mmascher-dev6_0
Task status:			QUEUED	on schedd: crab3-5@vocms059.cern.ch
```

The task is still in the taskworker queue, the schedd does not know anything about the task and might even change in case of failure.

Should we show the schedd name only if the status of the task is not `QUEUED`?

**Comment by belforte** [comment]
@mmascher the schedd name is in the structure, I did not make it up.
Why did TW assign a schedd already ? If this means "queued in front of that
schedd", i.e. vocms059 will be tried next, I think the message is correct.

**Comment by mmascher** [comment]
yes, that's what it means. That's probably ok, provided we keep in mind (and users understand) QUEUED on vocms059 means the tasl has not been submitted yet (which probably makes sense)

Closing the issue. BTW if you do not write "for" in the ommit message and just (Fixes #NNNN od Fix #NNNN) the issue gets closed once I merge the pull

**Comment by belforte** [comment]
closed via 
https://github.com/dmwm/CRABClient/pull/4525#event-370626016
