### ISSUE TITLE
Data returned by --json argument is not valid json

### ISSUE THREAD

**Issue by riga** [dmwm/CRABClient#4533]
Hi crab3 developers,

I just discovered some strange behavior when querying the status via:
```shell
crab status --json
```
The data I get (besides some task infos) looks like:
```
{
  '24': {
    'Retries': 1,
    'WallDurations': [2056.0, 2151.0],
    'StartTimes': [1438549220.0],
    'SubmitTimes': [1438549031.0, 1438551346.0],
    'JobIds': ['2435165.0', '2435877.0'],
    'EndTimes': [1438551276.0],
    'Restarts': 0,
    'RecordedSite': False,
    'State': 'idle',
    'ResidentSetSize': [94996, 77940],
    'TotalUserCpuTimeHistory': [15, 0.0],
    'SiteHistory': ['T1_US_FNAL', 'Unknown'],
    'TotalSysCpuTimeHistory': [0, 0.0]
  },
  ...
```

Users like me may want to parse this output, e.g. with ``json.loads``. However, single quotation marks and captialized ``True`` or ``False`` are not valid json. Atm, I overcome this by

```python
 json.loads(s.replace("'", '"').replace(": True,", ": true,").replace(": False,", ": false,"))
```
but I think this bug (?) should rather by fixed by crab.

Off-topic:
Is there some kind of *secret* argument to print only the json encoded status string?

**Comment by bbockelm** [comment]
Looks like the code that prints out the result is really printing the python dictionary without encoding it:

https://github.com/dmwm/CRABClient/blob/bfe2ce248cc9c748680abd918a3298054ceae464/src/python/CRABClient/Commands/status.py#L95

Not clear if there's any clever way to only print out the json output - might just have to scan for '{'.

**Comment by mmascher** [comment]
Hi @riga I took care of the `'` instad of `"`, thank you very much for spotting this and for spending some time to let us know.

About printing only the json when `--json` is used it makes sense to me. Although for scripting there is the so called crab libraru library (https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRABClientLibraryAPI), and in my opinion the --json flag should be deprecated.

**Comment by riga** [comment]
Thanks for fixing this and for mentioning the crab lib API!
