### ISSUE TITLE
Delete glidemon url from crab status

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4542]
As announced and agreed at the CRAB3 meeting, at the DMWM release planning meeting[1], and at the Project office meeting[2] we will remove the glidemon url in September. After that at some point glidemon will be shut down (up to Dima decide when after September)

That said let's start removing the url now. Also, we should probably announce that to the users, @AndresTanasijczuk , can you update the CRAB3 release twiki and mention that gilidemon will be "deprecated" please: https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3Releases#What_to_expect_in_CRAB_v3_3_1509

@belforte @evw , should we also send an announcement on computing-tools ?

[1] https://twiki.cern.ch/twiki/bin/view/CMS/DMWMReleasePlanning201506#CRAB3 (first bullet, first sub-bullet)
[2] https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompProjOfficeNews (second bullet Jul 7)

**Comment by belforte** [comment]
Ain't worth an announcement. We are not breaking anything here 
On Aug 7, 2015 12:49, Marco Mascheroni <notifications@github.com> wrote:As announced and agreed at the CRAB3 meeting, at the DMWM release planning meeting[1], and at the Project office meeting[2] we will remove the glidemon url in September. After that at some point glidemon will be shut down (up to Dima decide when after September)

That said let's start removing the url now. Also, we should probably announce that to the users, @AndresTanasijczuk , can you update the CRAB3 release twiki and mention that gilidemon will be "deprecated" please: https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3Releases#What_to_expect_in_CRAB_v3_3_1509

@belforte @evw , should we also send an announcement on computing-tools ?

[1] https://twiki.cern.ch/twiki/bin/view/CMS/DMWMReleasePlanning201506#CRAB3 (first bullet, first sub-bullet)
[2] https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompProjOfficeNews (second bullet Jul 7)

**Comment by AndresTanasijczuk** [comment]
Add to the releases twiki: https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3Releases#Improvements_enhancements_change
