### ISSUE TITLE
Simplify the way of passing options to a crab command in crabCommand

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4577]
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1159.html

We should make passing options to a crab command via crabCommand the most intuitive and simple as possible. Current situation is https://github.com/dmwm/CRABClient/blob/3.3.1511/src/python/CRABAPI/RawCommand.py#L12 which accepts the following possibilities:

* Suppose all options I pass require a value:
1) crabCommand('\<command\>', optname1=optvalue1, optname2=optname2) which uses "kwargs"
The client API then puts all arguments in a list: ['--optname1', optvalue1, '--optname2', optvalue2]
2) crabCommand('\<command\>', '--optname1=optvalue2', '--optname2=optvalue2') which uses "args"
The client API then puts all arguments in a list: ['--optname1=optvalue1', '--optname2=optvalue2']
3) crabCommand('\<command\>', '--optname1', optvalue1, '--optname2', optvalue2) which uses "args"
The client API then puts all arguments in a list: ['--optname1', optvalue1, '--optname2', optvalue2]

* Suppose some options do not require a value, then the user is forced to pass those before the keyword arguments:
1) crabCommand('\<command\>', '--optname1', optname2=optname2) which uses "args" and "kwargs"
The client then puts all arguments in a list: ['--optname2', optvalue2, '--optname1']
2) crabCommand('\<command\>', '--optname1', '--optname2=optvalue2') which uses "args"
The client then puts all arguments in a list: ['--optname1', '--optname2=optvalue2']
3) crabCommand('\<command\>', '--optname1', '--optname2', optvalue2) which uses "args"
The client then puts all arguments in a list: ['--optname1', '--optname2', optvalue2]

In the hypernews issue I pasted above I told the user that I will document examples of how one can pass options to the command in crabCommand. But I am now inclined to not document anything and fix this issue already in December release as I think it is very easy.

I propose to simplify crabCommand to accept a unique format for the options/arguments to the command. For example:

crabCommand(command, argsstr)

So the user will have to call crabCommand with the following syntax:

crabCommand('\<command\>', '--optname1=optvalue1 --optname2 --optname3 optvalue3 arg1 arg2')
We will take cmdargsstr and make a list by just splitting it (using empty space as separator): ['--optname1=optvalue1', '--optname2', '--optname3', 'optvalue3', 'arg1', 'arg2']

So the code I propose is:
```
def crabCommand(command, argsstr=None):
    """ crabComand - executes a given command with certain arguments and returns
                     the raw result back from the client.
    """
    args = argsstr.split() if argsstr else []

    return execRaw(command, args)
```

**Comment by belforte** [comment]
If I understand correcty, you say that when one would have typed
 `crab <command>  --optname1=optvalue1 --optname2 --optname3 optvalue3 arg1 arg2`
its should be possible to do the same inside a python script with:
 `status = crabCommand(command,'--optname1=optvalue1 --optname2 --optname3 optvalue3 arg1 arg2')`

is that so ?
shouldn't we have this code to parse the string already in the client, simply to check that
same parsing rules should be applied, whatever they are wrt spaces, commas etc.

By the way, this sounds so reasanbole, that I am curious why the current configuration is so much more complicated, was it done in the attempt to solve some oher problem which we may be overlooking now ?

**Comment by AndresTanasijczuk** [comment]
To your question "Is that so?" my answer is "yes".

**Comment by AndresTanasijczuk** [comment]
I think I see now why the current configuration is the way it is. When one uses the CRABAPI in a multicrab script to submit tasks like documented for example in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3AdvancedTutorial#Exercise_6_CRABAPI_library, one has the CRAB configuration already in a WMCore.Configuration object (named `config`) instead of having a configuration file. Therefore being able to do `crabCommand(command, config = config, ....)` is important.
If we would change crabCommand to take the command arguments in a string as I proposed, the user would have to first save the `config` object into a file. So in the multicrab script he would need to do:
```
from WMCore.Configuration import saveConfigurationFile

crabConfigFileName = "<something>"
saveConfigurationFile(config, crabConfigFileName)
argsstr = "--config=%s --optname2 --optname3 optvalue3 arg1 arg2" % (crabConfigFileName)
status = crabCommand("submit", argsstr)
```

**Comment by belforte** [comment]
Indeed going through the file appears quite ackward. 
Can we simply accept 
`status = crabCommand('submit',dryrun=True) `
and print some enlightening error message if `=True` is missing ?

What mostly disturbs me is that  the docuemntation
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRABClientLibraryAPI#The_crabCommand_API
has only examples. A proper definition would help.

In the end a CLI may accept the presence of an option to indicate a logical value (I want this feature enabled), but in the code variables can't "exist", they need to have a value.

**Comment by belforte** [comment]
back to the intial comment https://github.com/dmwm/CRABClient/issues/4577#issue-118417338
one thing I do not understand/like is the many ways of passing arguments, all of these appear acceptable:
```
crabCommand('submit',sitewhitelist='T2*')
crabCommand('submit','--sitewhitelist','T2*')
crabCommand('submit','--sitewhitelist=T2*')
```
that's of course very confusing. And if it works by accident, sort of be it, but let's make sure me make it clear which one is the correct way, since at some point we want to be free to change the interface so that only e.g. the first (and last ?) one works.
But if all that flexibility is intentional, I fear that we made the crabCommand interface more complex that it has to be.

**Comment by AndresTanasijczuk** [comment]
From your last two comments, I propose we accept only the following:
```
crabCommand('submit', optname1=optval1, optname2=optval2, ...)
```
meaning that for options that don't require a value (e.g. `--dryrun`) when running crab from the command line, we accept `dryrun=True` and `dryrun=False` in crabCommand. But we will have to assume that if optval == True or False then the option optname doesn't require a value and we internally replace it with `--optname`; otherwise we use the already existing replacement `--optname=optval`.

**Comment by belforte** [comment]
long discussion among Andres, Marco and Stefano.
Summary:
A) currenly users can do
```
crabCommand('submit', '--dryrun', optname1=optval1, optname2=optval2, ...)
```
and (IIUC) need to put the positional arg `'--dryrun'` before any `key=value` one

B) we will add support for
```
status = crabCommand('submit', dryrun=True, optname1=optval1, optname2=optval2, ...)
```
i.e. any option that can be put in the crab CLI without a value can be passed to the crabCommand API by assigning it the `True` value. This allows uniform syntax and to put this anywhere in the list.

C) we discussed way in which CRAB command and API could be made more elegant or more functional or more easy to maintain or all of that, but all of what was proposed is not backward compatible and thus would require a very significant transition effort. So all postponed to the time a compelling reason arise

Finally, for the record, and w/o Stefano trying to write a PR at this time, the way to implement B) would be to change
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABAPI/RawCommand.py#L18-L20
so that if `key` has a bollean value and it is `True`, then `--key` is appended to `arguments, otherwise it is ignored.
e.g. from
```
    for key, val in kwargs.iteritems():
        arguments.append('--'+str(key))
        arguments.append(val)
```
to:
```
    for key, val in kwargs.iteritems():
        if isinstance(val, bool):
           if val: arguments.append('--'+str(key))
        else
          arguments.append('--'+str(key))
          arguments.append(val)
```
