### ISSUE TITLE
prepare spec file for light weight crab client

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4583]

**Comment by mmascher** [comment]
Codewise we need the following PR to make sure we do not depend on httplib2 (unmantained unofficial package on googledoc):
https://github.com/dmwm/CRABServer/pull/5185
https://github.com/dmwm/CRABClient/pull/4606
https://github.com/dmwm/WMCore/pull/6742
httplib2 is not available in the CMSSW environment.

**Comment by belforte** [comment]
FOr lack of better place.
Note about lightweight client:

WE NEED TO KEEP HEAVYWEIGTH SETUP AROUND FOR THOSE FEW OLD CMSSW RELEASES (like CMSSW_5_3_18) WHICH BREAK libssl3.so FOR GRID COMMANDS
see e.g.
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1611/1/3.html

**Comment by belforte** [comment]
I was wrong. Even with full heavyweight crab3 setup, CMSSW_5_3_x with x<20 breaks myproxy-* in a way that we can't recover. Basically it ships a bad version of libssl3.so .

**Comment by belforte** [comment]
@mmascher @emaszs can we close this ?

**Comment by emaszs** [comment]
Yeah, @mmascher made sure that Bockjoo scripts take the crab_light file from our repo according to the version that is in the crabclient.spec file, at least that's my understanding. A separate spec file isn't necessary at the moment.
