### ISSUE TITLE
crab checkwrite has a wrong help msg from --checksum option

### ISSUE THREAD

**Issue by jmarra13** [dmwm/CRABClient#4587]
help for this option says to provide true or false, but the correct value is yes or no

this is the output of my validation script for the client:

----Checking crab checkwrite with --checksum option
You specified to use true checksum. Only lowercase yes/no is accepted to turn ADLER32 checksum
ERROR:  crab checkwrite with --checksum is broken in this release

and this is the current help msg on the client:

crab checkwrite -h
Usage: crab checkwrite [options] [args]

     Let user to test if he/she have permission to write on specify site

Options:
  -h, --help           show this help message and exit
  --site=SITENAME      The PhEDEx node name of the site to be checked.
  --lfn=USERLFN        A user lfn address.
  --checksum=CHECKSUM  Set it to true if needed. If true will use ADLER32
                       checksumAllowed values are yes/no. Default is yes.
  --command=COMMAND    A command which to use. Available commands are LCG or
                       GFAL.
  --proxy=PROXY        Use the given proxy. Skip Grid proxy creation and
                       myproxy delegation.
  --voRole=VOROLE      
  --voGroup=VOGROUP

**Comment by belforte** [comment]
oddiliy enough the message appear twice in the code base. I hate to do same change in two places
```
belforte@lxplus089/CRABClient> find . -name '*py' -exec grep ADLER32 {} \; -print
                               help = 'Set it to true if needed. If true will use ADLER32 checksum' +\
                self.checksum = 'ADLER32' if self.options.checksum == 'yes' else None
                msg = "You specified to use %s checksum. Only lowercase yes/no is accepted to turn ADLER32 checksum" % self.options.checksum
./src/python/CRABClient/Commands/checkwrite.py
                                help = 'Set it to true if needed. If true will use ADLER32 checksum' +\
                self.checksum = 'ADLER32' if self.options.checksum == 'yes' else None
                msg = "You specified to use %s checksum. Only lowercase yes/no is accepted to turn ADLER32 checksum" % self.options.checksum
./src/python/CRABClient/Commands/getcommand.py
belforte@lxplus089/CRABClient> 

```

**Comment by belforte** [comment]
OK. that's becasuse two commands (get and checkwrite) support the --checksum option
