### ISSUE TITLE
Enhance --json output

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/CRABClient#4601]
```crab status --json``` dumps the json to the default logger, which means there's not an easy way to actually use that output (I end up grepping the output from the client, which is brittle). It would be nice/handy if the json output could somehow be separated. Perhaps by changing/writing to a different logger, or by allowing the user to specify a file to write the json to.

Related, not all of the commands support ```--json```. Adding that functionality to report/tasks would be nice as well.

**Comment by belforte** [comment]
can't you simply use python API which is supposed to return a python object ?

**Comment by PerilousApricot** [comment]
Sure, it's possible, but the option's there, it should be functional :smile:

Oh the other hand, loading via crab-env-bootstrap.sh means that CRAB's python libraries aren't in PYTHONPATH (though that becomes not an issue depending on how the lightweight client works out).

**Comment by belforte** [comment]
since lightweight client works,  I think the answer is to use pyhon crab API
