### ISSUE TITLE
talk with CMSSW developers about SCRAM tree

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4627]
We need to know how to make a tarball from scrm release directory picking all the useful stuff and no extra junk for shipping with the job.
Need to talk with e.g. Shazad or David Abd...
Our current code is in
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/JobType/UserTarball.py

And an example of the issues we want to avoid is
https://hypernews.cern.ch/HyperNews/CMS/get/softwareDistrib/734.html
(which got no reply in 5 months, so f2f action seems better).

@emaszs let me know if you want to use this to get (more) aquainted with people on Bat 8 mezzanine, or if you prefer that I do this when at CERN.

**Comment by emaszs** [comment]
Yeah, I'll ping them, David Abdurachmanov is lithuanian after all :)

**Comment by emaszs** [comment]
Talked with David, in the issue that the user had, there is no SCRAM tree involved AFAIU. We were simply missing the `cfipython` folder, which may contain some user-generated code files. They're briefly described in a twiki [1].

[1] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideConfigurationValidationAndHelp#Introduction

**Comment by belforte** [comment]
this is well understood and under control by now
