### ISSUE TITLE
make sure config.Data.outLFNDirBase is validated against Lexycon

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4655]
see:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2379.html

In particular:

config.Data.outLFNDirBase =
'/store/user/rshevche/ALCARECO/MC/MinBias_TTbar/PhaseI.Test16.1105/'

results in
AssertionError:
'/store/user/rshevche/ALCARECO/MC/MinBias_TTbar/PhaseI.Test16.1105/TTbar_13TeV_TuneCUETP8M1_13TeV-pythia8/RunIIPixelPhase1-CMSSW_8_1_0_pre16-81X_upgrade2017_realistic_v22/161205_145916/0001/TkAlMinBias_1732.root'
does not match regular expression
/store/results/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\.\-_]+)/([A-Z\-_]+)/([a-zA-Z0-9\-_]+)/([0-9]+)/([a-zA-Z0-9\-_]+).root

which I checked with this ptyhon:
>>> from WMCore import Lexicon
>>> fn='/store/user/rshevche/ALCARECO/MC/MinBias_TTbar/PhaseI.Test16.1105/TTbar_13TeV_TuneCUETP8M1_13TeV-pythia8/RunIIPixelPhase1-CMSSW_8_1_0_pre16-81X_upgrade2017_realistic_v22/161205_145916/0001/TkAlMinBias_1732.root'
>>> Lexicon.lfn(fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp2/lib/python2.7/site-packages/WMCore/Lexicon.py", line 363, in lfn
    return check(storeResultsLFN, candidate)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp2/lib/python2.7/site-packages/WMCore/Lexicon.py", line 448, in check
    "'%s' does not match regular expression %s" % (candidate, regexp)
AssertionError: '/store/user/rshevche/ALCARECO/MC/MinBias_TTbar/PhaseI.Test16.1105/TTbar_13TeV_TuneCUETP8M1_13TeV-pythia8/RunIIPixelPhase1-CMSSW_8_1_0_pre16-81X_upgrade2017_realistic_v22/161205_145916/0001/TkAlMinBias_1732.root' does not match regular expression /store/results/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\.\-_]+)/([A-Z\-_]+)/([a-zA-Z0-9\-_]+)/([0-9]+)/([a-zA-Z0-9\-_]+).root

**Comment by emaszs** [comment]
@belforte, you added a check on the server for the complete output LFNs [*], that probably solves this issue too.

[*] https://github.com/dmwm/CRABServer/commit/6ea4ffc47497ef2f849edc55d21dd9af5d22461a

**Comment by belforte** [comment]
likely. I will check and hopefully close. Thanks

**Comment by belforte** [comment]
OK. The example in this issue
```
config.Data.outLFNDirBase = '/store/user/rshevche/ALCARECO/MC/MinBias_TTbar/PhaseI.Test16.1105/'
```
triggers the new check. In a way it is nice to catch bad configuration in the client,  but the check on the server is more thorough since it takes into account also the additional fields added by CRAB, which may be important if overall length limit is exceeded.
