### ISSUE TITLE
print tarball size in log before uploading

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4666]
add it before this line
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/JobType/Analysis.py#L151
size limit is only enforced in server, but at times uploading may fail due to size and currently there is not telling message. Printing the size in the log will at least allow experts to pin the problem immediately. See  e.g.
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2560/2.html

**Comment by belforte** [comment]
at the line I indicated the tarball file is still open and size is 0, need to put the message after file is closed
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/JobType/UserTarball.py#L140

**Comment by belforte** [comment]
this fixes #4669

**Comment by mmascher** [comment]
I think it also worth checking the size of the sandbox and complain if it is >100Mb. A user just wrote to me in private and it turned out he was uploading a 8Gb sandbox. It is bad we are only checking in the server..

**Comment by belforte** [comment]
I am pretty sure that I had this discussion already (can't remember if with you or Spiga/Cinquilli though) and developers position at the time was "keep client light since size is checked in server". Good that we are on same page now.
We  need to make sure that the limit is written in that small part of server code which is shared with client.
I'll take care.

**Comment by mmascher** [comment]
In this case it makes sense to have the check in both places. In general I believe that checks should be in the server if possible.

**Comment by belforte** [comment]
it will be easier for me to keep track with a new isee, and leave this closed, since it was merged already. So am closing again and will open a new one.
