### ISSUE TITLE
CRAB Client API backward compatibility broken

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4698]
Apparently after last release, crab API returns a ntuple instead of a dictionary[1].
This broke HammerCloud and I am puzzled that other users have not complained yet.
HammerClould people had to patch their code in a hurry because all tests stopped working suddenly. That's clearly something unacceptable.
Do we use client API in the validation ?

[1]
```
>>> statusresult = crabCommand('status', dir = crab_work_dir)
>>> type(statusresult)
<type 'tuple'>
>>> type(statusresult[0])
<type 'dict'>
>>> len(statusresult)
2
>>> type(statusresult[1])
<type 'dict'>
>>> statusresult[1]
{'jobList': [['finished', '1'], ['finished', '2']], 'jobsPerStatus': {'finished': 2}}
>>> statusresult[0]
{'status': u'SUBMITTED', 'username': u'belforte', 'jobs': {'1': {'State': 'finished'}, '2': {'State': 'finished'}}, 'jobsPerStatus': {'finished': 2}, 'taskWarningMsg': u'[]', 'schedd': u'crab3@vocms0106.cern.ch', 'publicationFailures': {}, 'collector': u'cmsgwms-collector-global.cern.ch:9620,cmssrv221.fnal.gov:9620', 'proxiedWebDir': u'https://cmsweb.cern.ch/scheddmon/0106/cms1627/170424_173550:belforte_crab_20170424_193545', 'statusFailureMsg': '', 'taskFailureMsg': None, 'inputDataset': u'/GenericTTbar/HC-CMSSW_7_0_4_START70_V7-v1/GEN-SIM-RECO', 'userWebDirURL': u'http://vocms0106.cern.ch/mon/cms1627/170424_173550:belforte_crab_20170424_193545', 'ASOURL': u'https://cmsweb.cern.ch/crabserver/prod', 'publication': {'disabled': []}, 'submissionTime': 1493055350, 'command': u'SUBMIT', 'outdatasets': u"['/GenericTTbar/belforte-CRAB3_test-SB-bb695911428445ed11a1006c9940df69/USER']", 'publicationEnabled': False}
>>> 

```

**Comment by belforte** [comment]
to be clear, we need to answer the usual questions here (urgently):
A) do we need to remedy ? how ? i.e.
  1. will anybody else be affected ?
  2. if yes to above:  how serious and what can we do ?
B) what do we have to do so that it does not happen again ?

**Comment by belforte** [comment]
Note also
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRABClientLibraryAPI
where we write
```
 Returns:
    The return value of the invoked CRAB command, which should be always a python dictionary. 
```

**Comment by belforte** [comment]
indeed, looking at the example in the twiki,
the job list should be a key in the dictionary, not another dictionary in the ntuple

**Comment by emaszs** [comment]
Hmm, it's because we now return multiple values from status2.
`statusresult, _ = crabCommand('status', dir = crab_work_dir)` would behave correctly because here we ignore the second return value. I somehow assumed this would be backwards compatible, my bad. With some refactoring I can make this into a single return value as it was before if you think that's useful.

**Comment by belforte** [comment]
yes, the technical solution seems easy in here
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/status.py#L144
you can add a key to the dictionary with shortresult. It will not break anything.
But I would like to answer A) and B)
What do you mean "if that's useful", is someone using this API ? If yes, how can their code work ?
Why should we change the signature of a public method other than by mistake ?
I can't understand why this was done to begin with ! But do not care to explore the past now, let's only make sure we do better in the future.

**Comment by belforte** [comment]
actually shortResult is already part of statudict. Why is this ntpuple needed at all ?

**Comment by emaszs** [comment]
It isn't, the job status dictionary has a different structure than the list of lists shortResult gives.

**Comment by belforte** [comment]
???
surely the information is (or can be) there. Whether it is more convenient to wite it
in two ways or one..  I can't say.
```
statusDict = self.makeStatusReturnDict(crabDBInfo, '', shortResult, statusCacheInfo, pubStatus,
                                               proxiedWebDir)
return statusDict, shortResult
```
Does makeStatusReturnDict needs to add another key ? So be it.
Are you saying that makeStatusReturnDict throws away some info from shortResult so you need to pass it explicitely in addition ?

This is all not making sense. This new status + taskprocess has meant so much code for so long that whatever is needed to make this work, could surely be done, even if it takes 5 days of works.
Only two things matter:
The API output content must be documented.
The API must stay fully backward compatible or we need a major effort in dealing with users of the API.

Current release fails on both.
What can do to make sure it does not happen again ?

**Comment by belforte** [comment]
Thanks @emaszs for quick fix. But more important is to decide how to proceed.
HammerCloud was modified on Friday after they noticed no HC submitted on Thursday.
https://cern.service-now.com/service-portal/view-request.do?n=RQF0751630
Now HC is compatible with current API, while user scripts are likely not.
HC is a critical service for CMS Site monitoring.
HC developer will be away My 11-31, so we can not change things again during that time.

I am not sure if we want to rush this change ~now and ask Jarka to revert HC, or wait until June release.

That's way I asked  who else is affected. I am really surprised that users did not complain.

**Comment by belforte** [comment]
I am afraid we need to converge today.

**Comment by emaszs** [comment]
I have a few more fixes ready for backwards compatibility, plus I still need to implement the combined status logic. Hopefully after that is done and we hear no more complaints we can close.

**Comment by belforte** [comment]
In spite of the generic title, this issue was actually about the change of the API return object from a dictionary to an ntuple. I believe the fix was merged and deployed in production. So we should close and open new ones in case we find other problems. But let's not have issues where one has to read a very long thread to understand the connection with some code change.

**Comment by belforte** [comment]
fixed in https://github.com/dmwm/CRABClient/pull/4699
