### ISSUE TITLE
review how status is reported in API

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4702]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2859/1/1.html
the new status API reports 
```
{'status': u'SUBMITTED', 'username': u'tpook', ....
```
where the old one would have written
```
{u'status': u'FAILED', u'username': u'tpook' ....
```
i.e. new API reports as `status` the status on the server, not the DAG one.

Discussing with @emaszs he pointed out that old API creates a combinatino of task and dag status using a somehow complex logic.
Hopefully most of what was done in there, is now obsolete since we have task process, but we need to review this to make sure that we do not have gross, obvious inconsistencies like the one above.
In ubtle cases hopefully we simply do better now.

**Comment by belforte** [comment]
for reference, I paste here pointers to old implementation from the chat with @emaszs 
in the old version, this is the task status that gets filled in in this method and later returned to the client https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L459
the failures affect the task status https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L510-L527
 task status for finished tasks https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L580-L588
also https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L692-L693

**Comment by belforte** [comment]
I had a chat with @emaszs on this topic this morning.
Here's the executive  summary. @emaszs please review that I remembered correctly and if you agree, can you provide a time estimate for implementation ?

1. keep reporting ony one `'status'`key in the dictionary
2. until task status in database reaches SUBMITTED, report the status in DB as task status
3. when task is SUBMITTED, check if webdir info was put in DB by the dagbootstrap
4. if answer to 3 is yes, lookup status_cache file created by TaskProcess and report that
5. if answer to 3. is no, use a condor_query to check if dag bootstrap job is pending/running or crashed
6. after 5. if dag bootstrap is pending/running, report SUBMITTED
7. after 5. if dag bootstrap is crashed, report FAILED
8. if at any time can not talk to server, or to schedd, report UNKNOWN
9. it is up to the user to cache previsous status and use it in place of the new UNKNOWN
10. optionally we may add a key to the dictionary with `statusReason` as a way to propagate e.g. error messages like reason for UNKNOWN, but we currently disagree on whether this is really useful

**Comment by emaszs** [comment]
About point 8, I don't think it makes sense to report UNKNOWN here if we can't talk to the server, previously we used to throw an exception instead. There really isn't much to report about the task if the server is unreachable besides the taskname. Otherwise, if the task is still bootstrapping, if the TP has not run yet or if the schedd cannot be reached we should report UNKNOWN, yes. For these three cases I also actually add a `statusFailureMsg` to the return dict, I had kinda forgotten about that (it is also used by other code to report failures in commands that depend on the new status). These errors will probably be different from the old status (they used to come directly from the server) but something should be there as an explanation for these three cases. That kind of covers point 10 as well I hope.

Implementing this is dead simple of course but I'll have to spend some time testing it because I'm not 100% sure it covers everything. So maybe early next week I should put this in production.

**Comment by emaszs** [comment]
Otherwise I agree with your logic @belforte, thanks for writing it down.

**Comment by belforte** [comment]
hmm... if we do not return `'status':'UNKNOWN'` what do we do ? Throw an exception ? Are users of the API expected to catch exceptions, and do we tell them what to do ? Maybe this is OK, simply a measurement of my ignorance.
THanks for  `statusFailureMsg`, it may not be the most illustrative name (hard to tell staus is failed from asking for status did fail) but as long as it is documented in the API twiki OK. If it is still undocumented, maybe we can improve the name ?

**Comment by emaszs** [comment]
Yes, in case the server is down we throw an exception, that's perfectly fine and that's how it was before forever AFAICT. The statusFailureMsg is the key that was in the statusold dictionary, the name should probably stay the same.

**Comment by tobias-pook** [comment]
Hi @belforte ,
just a quick comment. We already use statusFailureMsg when handling API outputs. The fact that it is not documented in the Twiki does not mean we already use it :wink: . Users get "creative" once you give them certain functionality....
Here is an example for a python lib we use in different workflow tools in Aachen3A to work with crab3:
https://gitlab.cern.ch/aachen-3a/tools/blob/db_staging/python/crabFunctions.py

**Comment by emaszs** [comment]
@tobias-pook , are you sure that the `statusFailureMsg` is used in your CRAB3 wrappers? An example would help to see if the previous functionality can be salvaged, though if the status command fails, I don't think that heavily influences any further actions that can be taken (there's not much a script/user can do in that case besides waiting or raising an alarm and contacting crab support IMO). From your `crabFunctions.py` I see that you check for the existence of the taskFailureMsg, this of course is different from the status failure and more often than not specifies a problem which the user should look into. The taskFailureMsg should still be there and the contents/logic of it should not have changed with the new commands.

**Comment by belforte** [comment]
I am afraid I do not know the details of this taskFailureMsg. In the end we need to make sure that 
there is way for the user to be positively sure that status command worked. While when it did not, I 
do not think we can cover all possible cases in the reason string, but we should make it clear under 
which conditions we raise an exception vs. return a non null taskFailureMsg.

**Comment by emaszs** [comment]
`taskFailureMsg` is what's set by the task worker and put in the DB which the status can later retrieve. Identifying when the status fails is possible, if the server is down it will throw. If it can only find information from the DB, since it is not a complete failure, it will return the information from the DB (along with the `statusFailureMsg`) and everything else will be missing, which I believe matches the old behavior more or less.

**Comment by belforte** [comment]
@emaszs I think it will help if you write down a short documentation of the status API (all in all the most complex API given the large and varying result) from the user point of view. So that anybody who wants to use is finds in there what to make of the various possibilities. That will lead to convergence faster than arguing on various examples, IMHO. In other words, try to explain what we want to provide.
Better yet if you put an example  like (pseudocode just to give an idea, feel free to change):
```
try:
 dict=crabAPI("status")
except:
  tell what to do
# if no exception:
 if taskFailureMsg in dict: then
# deal with errors (provide a couple examples!)
 else:
# all fine, explain how to get the info from the dict and what the various status names mean
```

i.e. do not think about what are the reasons for this or that, but focus on what the user should do based on what we report. Once the contract with the user of the API is clearly defined, everything else is only a matter of "bug fixing".

**Comment by emaszs** [comment]
Of course, I'll write down what each of the dict keys should contain and what can likely happen when using the status api. But again, the user really can't do anything about the errors. If some information is missing, it's missing for good. Dealing with errors mainly means checking that the dict keys aren't empty AFAICT.

**Comment by emaszs** [comment]
Wrote some things here https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRABClientLibraryAPI#crab_status_API_description_and

**Comment by tobias-pook** [comment]
Hi @belforte  and @emaszs ,
The solution outlined on the Twiki page seems fine for me.
Regarding your question. In our current code we handle certain failure messages, e.g. in order to recreate a folder if the crab submission was not successful, but I think this should no be affected by your changes.

thanks,
Tobias

**Comment by belforte** [comment]
thanks @tobias-pook 
just be aware that so far the failure message text is not part of the API, i.e. may change at any time. As the example from Emilis shows, those are the way we communicate with the user and we may want to keep trying to make those as clear as possible. I guess it is all fine as long as you do not build a long living service which critically depends on the exact text.

@emaszs thanks for the writeup, looks very good to me. By the way, I am starting to thing that we may want to make CLI and API reporting more consistent. We can talk about it i the context of also reviewing how we report transfer and publication status.

**Comment by belforte** [comment]
@emaszs maybe we can close this now ? IIUC there's no action left to do

**Comment by emaszs** [comment]
Yes, let's close then
