### ISSUE TITLE
checkStatusLoop uses old status

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4711]
It needs to be revisited, otherwise the automatic splitting will always fail here (not a big deal actually, the --wait option is seldom used/not that fundamental imho)
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/ClientUtilities.py#L678

**Comment by belforte** [comment]
pinging @mmascher and @matz-e 
if you do not want to fix, of fixing is too much trouble, I have nothing against deprecating the --wait option

**Comment by belforte** [comment]
chatted wity @mmascher today. Since it is broken and nobody complains, clearly means nodody uses nor needs --wait. So we deprecate it.
