### ISSUE TITLE
checkwrite and getoutput not working when gfal-copy in non-system path

### ISSUE THREAD

**Issue by chwissing** [dmwm/CRABClient#4755]
Hi,
at DESY we provide Grid clients via CVMFS. In order to reach them the path needs to be adjusted properly. It looks like that crab client does not work properly, when gfal-copy is not found in the standard system path like /usr/bin. Find a typical error message below[*]. Appears to be an environment issue, the special path is not properly preserved.

Cheers, Christoph

[*]
rab checkwrite --site=T2_DE_DESY
     Will check write permission in the default location
     /store/user/<username>
     Retrieving DN from proxy...
     DN is: /C=DE/O=GermanGrid/OU=uni-hamburg/CN=XXXXXX
     Retrieving username from SiteDB...
     Username is: XXXXX
     Validating LFN /store/user/XXXXX...
     LFN /store/user/lbenato is valid.
     Will use `gfal-copy`, `gfal-rm` commands for checking write
permissions
     Will check write permission in /store/user/XXXXX on site
T2_DE_DESY

     Attempting to create (dummy) directory
     crab3checkwrite_20180416_131300 and copy (dummy) file
     crab3checkwrite_20180416_131300.tmp to /store/user/XXXXX

     Executing command: env -i X509_USER_PROXY=/tmp/x509up_u30466
     gfal-copy -p -v -t 180
    
file:///afs/desy.de/user/l/lbenato/LongLivedTriggers/CMSSW_8_0_26_patch1/src/Analysis/ALPHA/crab3checkwrite_20180416_131300.tmp

    
'srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/XXXXX/crab3checkwrite_20180416_131300/crab3checkwrite_20180416_131300.tmp'

     Please wait...
     Failed running copy command
       Stderr:
         env: gfal-copy: No such file or directory
       
     Checkwrite Result:
     Unable to check write permission in /store/user/lbenato on site
     T2_DE_DESY

**Comment by belforte** [comment]
Is this something that always happened but was never reported, or should we look for some recent change ? I am puzzled because I thought nothing changed here in years.
The goal in crab client is to execute grid commands in the same env. in which crab command
was issued, does gfal-coipy work before the user types "crab submit" ?
I suspect there's no easy way for me to log in at DESY and check details, right ?
Just one question, is CVMFS for gfal-* mounted at login, and thus available in an empty env ? Or is some setup script executed vua .bashrc or similar ?

**Comment by chwissing** [comment]
Dear Stefano,
I am rather sure that the issue is there since 'ever', but was not reported. It only affects checkwrite (and also getoutput as I just learned). Both are not commonly used nor vital and all the rest of CRAB works.

The path to reach Grid clients in CVMFS is setup via sytem login scripts in /etc/. So everybody get them without any extra effort with local .bashrc. After sourcing CMS environment and CRAB environment gfal-* stuff still works:

> which cmsRun                  
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/bin/slc6_amd64_gcc630/cmsRun

> which crab
/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1804/bin/crab

> which gfal-copy
/cvmfs/grid.cern.ch/emi-ui-3.17.1-1.el6umd4v5/usr/bin/gfal-copy

I think the issue comes with the call of the external command in CRAB 'env -i X509_USER_PROXY=/tmp/x509up_u5729 gfal-copy ...', which wipes the customized path that reaches the Grid tools in CVMFS. I am recalling that WMCore suffered from a similar (if not the same issue). Some dirty trick was introduced, that saves the shell environment and puts it back, when external tools are called. You might want to take a look at WMCore:
https://github.com/dmwm/WMCore/blob/c2f3404c8b66357276b381c7472dacc130ef0887/src/python/WMCore/Storage/Backends/GFAL2Impl.py
and
https://github.com/dmwm/WMCore/blob/152e22eb389fbf1ce663db5d6753c0dbff8dc9d5/etc/submit.sh

Access to the National Analysis Facility (NAF) at DESY is by default only for members of German institutes (the name gives a hint). However we do allow for collaboration for certain projects according to some rules. If it would be helpful for you to have a NAF account, contact me directly. I am rather sure that we find a way to provide an account in agreement with the rules.

Cheers, Christoph

**Comment by belforte** [comment]
ah.. the dreaded env -i  :-( I surely do not want NAF users to be let down.
let me look at code and then we'll talk about debugging options :-)

**Comment by belforte** [comment]
I  believe we shoiuld simply do in crab client the same that we do before calling voms-proxy-info,
i.e. do a temporary scram unsetenv in order to restore the environment before scram env was called, and up to the user make sure that grid commands work before CMS stuff starts.
@chwissing do you have access to CERN's AFS from DESY ? If so I'll prepare a patched client in my AFS area for you to try.

**Comment by chwissing** [comment]
Ciao Stefano,
please install a test version of the client into AFS at CERN, that I can read. Relevant machines at DESY have AFS installed and can reach the CERN AFS cell.

**Comment by belforte** [comment]
I think I have fixed this, please test by using these lines after you setup crab:
```
export PATH=/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin:$PATH
export PYTHONPATH=/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/src/python:$PYTHONPATH
```
We can then push it in production

Stefano

**Comment by chwissing** [comment]
Stefano,
I cannot reach your new client due to AFS permissions. This also applies, when I try to read from CERN, where I have for sure a proper AFS token + Kerberos ticket. Perhaps you can give read access to cern:zh.
Christoph

**Comment by belforte** [comment]
AFS ACL's have been set to `system:anyuser rl` for all of /afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient but I think that some system crontab checks all directories and will overwrite this

**Comment by chwissing** [comment]
Things appear to work besides some Exception at the end, which seem not to harm. However it would be good to get rid of it in order not bother users with it.

% which crab                   
/afs/cern.ch/user/b/belforte/WORK/CRAB3/CRABClient/bin/crab

% crab checkwrite --site T2_DE_DESY
Will check write permission in the default location /store/user/<username>
Retrieving DN from proxy...
DN is: /O=GermanGrid/OU=XXXXXXXXXXXXXXXXXXXXXXXX
Retrieving username from SiteDB...
Username is: XXXXXXXX
Validating LFN /store/user/XXXXXXX..
LFN /store/user/cwissing is valid.
Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
Will check write permission in /store/user/XXXXXX on site T2_DE_DESY

Attempting to create (dummy) directory crab3checkwrite_20180423_154942 and copy (dummy) file crab3checkwrite_20180423_154942.tmp to /store/user/XXXXXXXXX

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-copy -p -v -t 180 file:///afs/desy.de/user/w/XXXXXX/Grid/CMS/CMSSW_7_0_6/src/crab3checkwrite_20180423_154942.tmp 'srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/XXXXXXX/crab3checkwrite_20180423_154942/crab3checkwrite_20180423_154942.tmp'
Please wait...

Successfully created directory crab3checkwrite_20180423_154942 and copied file crab3checkwrite_20180423_154942.tmp to /store/user/XXXXXX

Attempting to delete file srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/XXXXXXX/crab3checkwrite_20180423_154942/crab3checkwrite_20180423_154942.tmp

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -v -t 180 'srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/XXXXXX/crab3checkwrite_20180423_154942/crab3checkwrite_20180423_154942.tmp'
Please wait...

Successfully deleted file srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/XXXXX/crab3checkwrite_20180423_154942/crab3checkwrite_20180423_154942.tmp

Attempting to delete directory srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/XXXXXX/crab3checkwrite_20180423_154942/

Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -r -v -t 180 'srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/XXXXXX/crab3checkwrite_20180423_154942/'
Please wait...

Successfully deleted directory srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/XXXXXXX/crab3checkwrite_20180423_154942/

Checkwrite Result:
Success: Able to write in /store/user/XXXXXX on site T2_DE_DESY
Exception AttributeError: AttributeError("'NoneType' object has no attribute 'rmtree'",) in <bound method TempDirectory.__del__ of <WMCore.Services.Requests.TempDirectory object at 0x14f4e50>> ignored

**Comment by belforte** [comment]
Thanks a lot Christoph, we'll deploy in CVMFS
As to the exception at the end it is indeed harmless but annoying and is there in current client since last summer, anyhow we just fixed that regression and next client will have that as well.
