### ISSUE TITLE
ERROR: KeyError: 'OriginalConfig' in a `crab remade` task

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABClient#4757]
`crab remake` does not add the 'OriginalConfig' [key](https://github.com/dmwm/CRABClient/blob/ab8b51638a77c4a06d081352d6e451a5cc28ed1b/src/python/CRABClient/ClientUtilities.py#L426) in the '.requestcache' file and so `crab status --jobids` crashes here:
 https://github.com/dmwm/CRABClient/blob/34b75492554b093e633ec9d4e0e6501258f86f3b/src/python/CRABClient/Commands/status.py#L149

**Comment by belforte** [comment]
after quick look at code with @lecriste , this is not trivial since the original configuration will have to be pulled from server. Clearly possible since crab server UI does it. But lots of stuff for us to learn there.

**Comment by lecriste** [comment]
Probably pulling from the server is not necessary: we can fetch the splitting algorithm as we do for other parameters:
https://github.com/dmwm/CRABClient/blob/c7c4fdd93807b250d0069607a69b3e9070b9a566/src/python/CRABClient/Commands/status.py#L51-L61

The key is 'tm_split_algo': 
https://github.com/dmwm/CRABServer/blob/5e6922782ffab85738aad5ea3b52e0aa12a3883d/src/python/TaskWorker/TaskManagerBootstrap.py#L47

@belforte do you agree?

**Comment by belforte** [comment]
fetch from DB ad pull from server are two names for the same thing indeed.
Thanks @lecriste for having quickly gone over the "lots of stuff to learn" !
Yes, this would be the correct solution.

**Comment by belforte** [comment]
resolved in https://github.com/dmwm/CRABClient/issues/4774
