### ISSUE TITLE
beware of config.JobType.maxJobRuntimeMin in automatic splitting

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4771]
I found that if the crabconfiguration indicates a value for config.JobType.maxJobRuntimeMin,
that value is then used in the processing DAG submission, which can lead to very obscure failure.
I do not suggest to fix this this in the automatic splitting code now, but we should
1. add to documenation
1. raise an error at crab submit time
which surely is easier and less risky than touching the automatic splitting code

**Comment by lecriste** [comment]
Change in documentation:
https://twiki.cern.ch/twiki/bin/rdiff/CMSPublic/CRAB3ConfigurationFile?rev2=62&rev1=63&render=sequential
