### ISSUE TITLE
update to latest WMCore 1.1.16

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4781]
CRAB client on CVMFS has dependecy on WMCore as well , see
https://twiki.cern.ch/twiki/bin/view/CMSPublic/NotesAboutReleaseManagement#Releasing_a_CRABClient_release_c

we should make sure that we can build it and that it works with WMCore tag 1.1.16 and update the spec files

**Comment by lecriste** [comment]
Closed via https://github.com/cms-sw/cmsdist/pull/4320
