### ISSUE TITLE
Smaller tarballs with CRAB

### ISSUE THREAD

**Issue by aminnj** [dmwm/CRABClient#4783]
Hi,

Sorry if this is not the right place. Prompted by [this HN](https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4145.html) and also personal experiences, I am wondering if CRAB has explored using bz2 instead of gzip for tarring. In particular, using `mode='w:bz2'` in https://github.com/dmwm/CRABClient/blob/7a83a98ae92e568b6c01db4d968109c15c0c231b/src/python/CRABClient/JobType/UserTarball.py#L37
(In the python2 version of the `tarfile` package, those are the only 2 algorithms. python3 adds lzma support.)

Some time ago, I copied CRAB's implementation to make CMSSW tarballs for use with condor at my local cluster. With recent CMSSW recipes/neural net libraries/etc, my tarballs have grown, and I found switching from gzip to bz2 can decrease the size of the tarball by almost a factor of 2 in the handful of cases that I've tested. And if the tarballs are extracted with the `tarfile` package `extractall()`, no further change is needed. Well, in my case, nothing other than `tar xzf blah.tar.gz` to `tar xf blah.tar.gz` in some of my shell scripts.

As for compression time, I haven't checked rigorously, but I don't feel much of a difference using bz2 wrt gzip.

Nick

**Comment by belforte** [comment]
Thanks for the input, we never considered this.
Indeed it should be quite simple, the most appealing part being that it only a client side change.
I guess server code is old enough that `z` was required in `tar xzf`, mybe from SL5 (or SL4) times ?
We should give this a try.
Any volunteer ?

**Comment by belforte** [comment]
I thought I had removed z option from untar commands in server,
but it came out I have not yet. So we need to do that before.
Let's open a server issue and once server is capable to handle
any compression we'll change the client.

**Comment by belforte** [comment]
@lecriste if I did thing correctly, production CRAB is now capable to deal with bzip2 compression. So we should give this a try and if we see that it have no problem afer some externsive tests, change the default compression.
@aminnj you are certainly also welcome to give it a try, the more the better. The major problems with changes to CRAB is that at times there is some hidden part of the code which is only executed when some particular issue happen, that we fail to notice and to check early enough.

**Comment by belforte** [comment]
when testing I get:in job stdout:
== CMSSW: Couldn't untar sandbox with python2: 1
so I must have missed some place where untarring happens. back to https://github.com/dmwm/CRABServer/issues/5729

**Comment by belforte** [comment]
Waiting for a new WMCore tag and a new TW tag at this point. Client side this is OK, but can't merge until server is ready.

**Comment by belforte** [comment]
Note bzip2 may not necessarely result in significantly smaller tarballs: https://github.com/dmwm/WMCore/pull/8954#issuecomment-448101472
Maybe we can stick with gzip and allow bzip2 as an option if the user goes over the limit

**Comment by belforte** [comment]
Server side owork is done, including new WMCore. We can now test against production server and then merge and close.

**Comment by belforte** [comment]
this is PR https://github.com/dmwm/CRABClient/pull/4787
