### ISSUE TITLE
allow to tune what goes in the sandbox

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4785]
from a disccusion on LPC support mail list:

```
One big sandboxing constraint: I can’t tell CRAB to sandbox any file I want. If it wasn’t going to add a file to the sandbox already (i.e. the file wasn’t in lib, src, etc.) than I can’t add it to the sandbox. I can send extra files along with the CRAB job, but I don’t have any control over where CRAB puts those files once it reaches the worker node. My command to access those extra files must be generic enough to pick them up where ever CRAB puts them.

 

Cheers,

Alexx

 

--

Alexx Perloff

Postdoctoral Associate

University of Colorado Boulder

Office: Wilson Hall 11W, Fermilab

Phone: 925-330-3828

Email: Alexx.Perloff@Colorado.edu

cid:image001.jpg@01D392D2.807D2930

 

 

From: Marguerite Tonjes <tonjes@fnal.gov>
Date: Friday, November 2, 2018 at 3:15 PM
To: Stefano Belforte <stefano.belforte@gmail.com>
Cc: Kevin Pedro <pedrok@fnal.gov>, Alexx Stephen Perloff <Alexx.Perloff@Colorado.EDU>
Subject: Re: LPC Computing discussion notes, Nov. 2, 2018

 

Sorry, I should have taken a little more time with the notes before sending them, but a lot of people were having problems with condor, so I wanted to share. I add Kevin and Alexx who I think can comment on what crab sandboxing is missing, and I'll be happy to correct the notes/minutes.

 

Please see below with Stephan's comments inline.

 

Yes, our current workaround for this problem with scram b ProjectRename is essentially crab sandboxing. I left out the part of the notes where we discussed why users even *want* to use condor instead of crab.

 

-Marguerite

------------------------------------------------------------------------------------------
Dr. Marguerite Tonjes                                        
LPC Computing Support                       https://lpc.fnal.gov/computing
tonjes@fnal.gov                                          
Skype: phMarguerite             CMS Experiment Mattermost: @belt
office: (630) 840-2859                              FNAL WH11E        

------------------------------------------------------------------------------------------

 

    On Nov 2, 2018, at 3:12 PM, Stefano Belforte <stefano.belforte@cern.ch> wrote:

     

    Hi Marguerite

    On 02/11/2018 14:58, Marguerite Tonjes wrote:

        - Comment: crab sandboxing is limited


    can you say how is it limited ? Is this something we can overcome ?
    is this what's written in next comment, that CFAB does not pick libraries
    which are not in ./lib ? or something more ?


        --> workaround for ProjectRename issues
        1) make sure tarball doesn't have .scram (--exclude="*.scram")
        2) In job: create new scram project (makes a new .scram area that points to that place)
        eval `scramv1 project CMSSW CMSSW_10_2_0`
        cd CMSSW_10_2_0
        3) Then unpacking tarball into that scram area
        cd CMSSW_10_2_0/src
        4) now do "cmsenv" eval `scramv1 runtime -sh`
        5) Run code


    IIUC, that's what CRAB does, aside from being a bit restricted as
    to what to tar from user side. Surely whjen sending sandboxes from LPC interactive
    modes to LPC batch nodes one can be less picky about file sizes !

    But I missed something, I'll be glad to be educated and improve the tool.

    Stefano

 ```

**Comment by belforte** [comment]
would a generalization of this parameter do ?

sendPythonFolder  |   boolean  |   Determine if the python folder in the CMSSW release ($CMSSW_BASE/python) is included in the sandbox or not. Defaults to False.

refs:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#What_are_the_files_CRAB_adds_to

**Comment by belforte** [comment]
I could let you indicate a directory name relative to  head of scram tree and tar everything in it.
I haven't looked at code yet, but was thinking of reusing what is there changing `python` to a user-specified string.
I would not like to pick one file here, one file there.

**Comment by aperloff** [comment]
I like the idea of leaving the sendPythonFolder alone because it serves a specific and necessary purpose. It sends a specific folder with a specific use. If you replaced the option, users who previously used the python folder and also want to make use of this new option would be out of luck. I would think this option would go alongside the sendPythonFolder option (i.e. sendUserSpecifiedFolder) which would do much the same thing, but is more in the users control.

While picking single files might be a pain, or even messy, it may be the best way to reduce the size of the sandbox. Why can't the option be able to pick a list of files and/or a list of folders? Doesn't tar treat them basically the same?

**Comment by belforte** [comment]
Yes, I will keep sendPython, was simply thinking of copy/paste+minimal changes.
What you suggest is basically to let user add arguments to tar command, the problem that I see is
dealing with errors, it may be trickier to master than indicating a directory name.
But if your use case is better addressed by a list of file/folders... we'll look into that.
thanks

**Comment by belforte** [comment]
back to this after 1 year... I looked at the code and found that there's also already an (undocumented, to fix) additional option to ask also for the 'external' folder to be added. Which is usually empty in the scram tree.
https://github.com/dmwm/CRABClient/pull/4640

so there are several places where additional files can be placed and user know where to find them, since the scram tree will be replicated in the worker node.

Given that, and the fact that there's no developer effort available for CRAB anymore. I am afraid that I have to close this.

**Comment by belforte** [comment]
I have added the  `JobType.sendExternalFolder`  parameter to the documentation
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile#CRAB_configuration_parameters
