### ISSUE TITLE
crab submit should print workdir

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4796]
just a though, I noiced that crab submit prints the task name but not
the working dir. Yet, if I want to excute crab status a bit later, I need the
working dir. I nevere really needed this in the past, because I would
just do ls and copy/paste, but now that I need to send working dir
to a different disk, I wish I had it printed there.
Yet I am unsure whether to request a change, since nobody ever
felt the same need (apparently), although I hope it is a simple chage.
@lecriste what do you think ?

```
cmslpc24:Convert$ crab submit
Will use CRAB configuration file crabConfig.py
Importing CMSSW configuration dummyPset.py
Finished importing CMSSW configuration dummyPset.py
Sending the request to the server
Success: Your task has been delivered to the CRAB3 server.
Task name: 190225_151234:belforte_crab_20190225_091144
Please use 'crab status' to check how the submission process proceeds.
Log file is /uscms_data/d2/belforte/crab_20190225_091144/crab.log
cmslpc24:
```

**Comment by belforte** [comment]
to be clear, I suggest to add one line below the `Task name:...` one and
possibly modify the line below to say `crab status -d <workdir>`

**Comment by lecriste** [comment]
If you issue the plain `crab status` command right after the `crab submit` one, it picks up the last submitted task, no need to specify the workdir.

**Comment by belforte** [comment]
yes, I know that !
two use cases I have so far:
1. I want to issue crab kill
2. I have submitted one or two more tasks and would find it handy to copy/paste from lines above on the screen

no big deal, I know. That's why I am asking for opinion rather then making a PR

**Comment by todor-ivanov** [comment]
I agree with Stefano. 
I was feeling the need of that during the submissions I make but knowing that crab keeps track only about the latest submission I usually simply create a script to keep track of the different batches of submissions. Which is an additional work. And having that info at hand can safe confusion for sure.

**Comment by lecriste** [comment]
Ok here it's the commit:
https://github.com/lecriste/CRABClient/commit/7bc868fced497584cb798bccf0fdf50e84e4c838

@belforte shall I merge?

**Comment by belforte** [comment]
@lecriste do not forget to make the PR with your commit

**Comment by lecriste** [comment]
`/cvmfs/cms.cern.ch/crab3/crab_pre.sh`
contains the PR.
