### ISSUE TITLE
add sanity check for unitsPerJob when using automatic splitting

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4797]
looks like when people convert scripts from other splitter to automatic,
of out of sheer ignroance, they put values of unitsPerJob in the O(10K or more) range,
which may be OK as lumi to process (in mini/nanoAOD) or event for MC,
but as minutes of running time results in jobs asking for many days, which
will never run.
Since this value is used in the subDag creation in PostJob, submissions there
avoid the sanity check done on maxWallTime in the user configuration.
This is very difficult for users to figure out, and takes some time also to experts.
So we should make a check in the client and refuse submission for values
larger than e.g. 45 hours = 2700 min

**Comment by lecriste** [comment]
I would implement also the check on the lower bound which now is made only in the TW:
https://github.com/dmwm/CRABServer/blob/631c55d6cc9f5aae1c73085b1e38051d00a4494c/src/python/TaskWorker/Actions/Splitter.py#L79-L83
