### ISSUE TITLE
Submission failing because of missing PSetDump.py

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABClient#4809]
As discussed here:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4782/1/1/1/1/1.html

`crab submit` fails because can not find `PSetDump.py`.

Relevant log lines:

DEBUG 2019-04-24 09:36:04,367: 	 Writing CMSSW configuration to /afs/cern.ch/work/c/cerminar/egml1/dev/cc7/ntuple_prod/CMSSW_10_5_0/src/submission/ntuples/v00/SinglePhoton_FlatPt-8to150_PU0/crab_SinglePhoton_FlatPt-8to150_PU0/inputs/PSet.py
DEBUG 2019-04-24 09:36:04,985: 	 Cannot dump CMSSW configuration file. This prevents sandbox recycling but it is not a fatal error.
ERROR 2019-04-24 09:36:04,985: 	 Sequence has a label, but using its label to get an attribute from the process yields a different object or None
label = hgcalBackEndLayer2
DEBUG 2019-04-24 09:36:04,986: 	 The following EDM output files will be collected: []
...
DEBUG 2019-04-24 09:36:13,422: 	 Adding data directory /afs/cern.ch/work/c/cerminar/egml1/dev/cc7/ntuple_prod/CMSSW_10_5_0/src/L1Trigger/VertexFinder/interface to tarball
ERROR 2019-04-24 09:36:13,787: 	 Unhandled Exception!
ERROR 2019-04-24 09:36:13,787: 	 [Errno 2] No such file or directory: '/afs/cern.ch/work/c/cerminar/egml1/dev/cc7/ntuple_prod/CMSSW_10_5_0/src/submission/ntuples/v00/SinglePhoton_FlatPt-8to150_PU0/crab_SinglePhoton_FlatPt-8to150_PU0/inputs/PSetDump.py'
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 148, in __call__
    self.cmd()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 102, in __call__
    dummy_inputfiles, jobconfig = plugjobtype.run(filecacheurl)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/JobType/Analysis.py", line 147, in run
    tb.addFiles(userFiles=inputFiles, cfgOutputName=cfgOutputName)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/JobType/UserTarball.py", line 105, in addFiles
    self.tarfile.add(os.path.join(basedir, BOOTSTRAP_CFGFILE_DUMP), arcname=BOOTSTRAP_CFGFILE_DUMP)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/python/2.7.14-omkpbe4/lib/python2.7/tarfile.py", line 2009, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/python/2.7.14-omkpbe4/lib/python2.7/tarfile.py", line 1883, in gettarinfo
    statres = os.stat(name)
OSError: [Errno 2] No such file or directory: '/afs/cern.ch/work/c/cerminar/egml1/dev/cc7/ntuple_prod/CMSSW_10_5_0/src/submission/ntuples/v00/SinglePhoton_FlatPt-8to150_PU0/crab_SinglePhoton_FlatPt-8to150_PU0/inputs/PSetDump.py'
ERROR 2019-04-24 09:36:13,790: 	 ERROR: OSError: [Errno 2] No such file or directory: '/afs/cern.ch/work/c/cerminar/egml1/dev/cc7/ntuple_prod/CMSSW_10_5_0/src/submission/ntuples/v00/SinglePhoton_FlatPt-8to150_PU0/crab_SinglePhoton_FlatPt-8to150_PU0/inputs/PSetDump.py'
ERROR 2019-04-24 09:36:13,791: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.

**Comment by belforte** [comment]
@lecriste I'd say we do in two steps:

1.   highprio: improve message and turn into a fatal error
2.  low prio: find out why exactly this is needed and check if there's a way to make the error non-fatal as the original implementor clearly expected

**Comment by belforte** [comment]
relevant code is here
https://github.com/dmwm/CRABClient/blob/e8870609c634b3ff444bed47a6cd086f9ab17d62/src/python/CRABClient/JobType/CMSSWConfig.py#L98-L101
maybe start by changing logging from debug to error and re-raise the exception ?

**Comment by belforte** [comment]
Let's split into two issue
Keep this as Cannot dump CMSSW configuration file shoudl be fatal.
Open a new one

**Comment by belforte** [comment]
closed by @lecriste via #4810
