### ISSUE TITLE
wrong publication statistics for multiple datasets

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4814]
when there is more than one dataset to publish in one task (two output files or more per job), crab status prints incorrect publish summary, see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4857/2.html

```
Task name:			190416_073131:scalzafe_crab_B0ToTau_To3Mu_beamspot14TeV_filterME0_padbased-step3_scram_corrected_2_100evt__HiStat0
Grid scheduler - Task Worker:	crab3@vocms0120.cern.ch - crab-prod-tw01
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/190416_073131%3Ascalzafe_crab_B0ToTau_To3Mu_beamspot14TeV_filterME0_padbased-step3_scram_corrected_2_100evt__HiStat0
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=scalzafe&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=190416_073131%3Ascalzafe_crab_B0ToTau_To3Mu_beamspot14TeV_filterME0_padbased-step3_scram_corrected_2_100evt__HiStat0
New dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=scalzafe&var-task=190416_073131%3Ascalzafe_crab_B0ToTau_To3Mu_beamspot14TeV_filterME0_padbased-step3_scram_corrected_2_100evt__HiStat0
In case of issues with the new dashboard, please provide feedback to hn-cms-computing-tools@cern.ch
Warning:			The following sites from the user site whitelist are blacklisted by the CRAB server: [u'T2_IT_Rome', u'T2_IT_Pisa']. Since the CRAB server blacklist has precedence, these sites are not considered in the user whitelist.
Status on the scheduler:	COMPLETED

Jobs status:                    finished     		100.0% (10000/10000)

Publication status:		done         		100.0% (20000/20000)
(from CRAB internal bookkeeping in transferdb)
				failed       		 50.0% (10000/20000)
				unsubmitted  		-50.0% (-10000/20000)

Output dataset:			/ME0trigger/scalzafe-B0ToTau_To3Mu_beamspot14TeV_filterME0_padbased-step3_scram_corrected_2_100evt__HiStat0_FEVTDEBUGHLToutput-f87dcb147e758f7fc82711831d90dfbb/USER
Output dataset DAS URL:		https://cmsweb.cern.ch/das/request?input=%2FME0trigger%2Fscalzafe-B0ToTau_To3Mu_beamspot14TeV_filterME0_padbased-step3_scram_corrected_2_100evt__HiStat0_FEVTDEBUGHLToutput-f87dcb147e758f7fc82711831d90dfbb%2FUSER&instance=prod%2Fphys03
Output dataset:			/ME0trigger/scalzafe-B0ToTau_To3Mu_beamspot14TeV_filterME0_padbased-step3_scram_corrected_2_100evt__HiStat0_MINIAODSIMoutput-f87dcb147e758f7fc82711831d90dfbb/USER
Output dataset DAS URL:		https://cmsweb.cern.ch/das/request?input=%2FME0trigger%2Fscalzafe-B0ToTau_To3Mu_beamspot14TeV_filterME0_padbased-step3_scram_corrected_2_100evt__HiStat0_MINIAODSIMoutput-f87dcb147e758f7fc82711831d90dfbb%2FUSER&instance=prod%2Fphys03
```

**Comment by belforte** [comment]
there lines with stats from transferdb are clearly wrong. Esp. given that count in DBS is OK.

**Comment by lecriste** [comment]
I found a bug in the math to get the number of files from the number of jobs.
Anyway count in transferdb does not look OK, see last line:
```
Task name:			190908_154130:scalzafe_crab_LeonardoCristellaProvaDigiStep3_0
Grid scheduler - Task Worker:	crab3@vocms0120.cern.ch - crab-prod-tw01
Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/190908_154130%3Ascalzafe_crab_LeonardoCristellaProvaDigiStep3_0
New dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=scalzafe&var-task=190908_154130%3Ascalzafe_crab_LeonardoCristellaProvaDigiStep3_0

Jobs status:                    failed       		 23.5% ( 2354/10000)
				finished     		 76.5% ( 7646/10000)

{u'status': {u'failed': 7646, u'done': 15292}}
```
@belforte how can we debug this?

**Comment by belforte** [comment]
keep in mind that transferdb has one entry per file, there can be more files then jobs.
Lat line looks me to indicate that 7646 jobs completed correctly, each asked to xfer 3 files,
and for each job one file always failed, while 2*7646=15292 did OK.
Does this help ?

**Comment by lecriste** [comment]
Makes sense but why 3 files per job instead of 2, as the numner of output dataset?

**Comment by lecriste** [comment]
See also this other example:
```
Task name:			190908_155035:scalzafe_crab_LeonardoCristellaProvaPadStep3_0
Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/190908_155035%3Ascalzafe_crab_LeonardoCristellaProvaPadStep3_0
New dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=scalzafe&var-task=190908_155035%3Ascalzafe_crab_LeonardoCristellaProvaPadStep3_0

Jobs status:                    failed       		 24.8% ( 2476/10000)
				finished     		 75.2% ( 7524/10000)

{u'result': [{u'status': {u'failed': 7525, u'done': 15047}}]}
```

**Comment by belforte** [comment]
2 root files + the log ? can you check a few failure logs in ?

**Comment by belforte** [comment]
as per discussion in chat:
the server UI pulls transfer info via this
https://github.com/dmwm/CRABServer/blob/master/src/script/task_info.js#L781

**Comment by belforte** [comment]
for the task above
Task name:			190908_155035:scalzafe_crab_LeonardoCristellaProvaPadStep3_0

Task URL : 	https://cmsweb.cern.ch/crabserver/ui/task/190908_155035%3Ascalzafe_crab_LeonardoCristellaProvaPadStep3_0

the transferInfo URL is:
https://cmsweb.cern.ch/crabserver/prod/fileusertransfers?username=scalzafe&taskname=190908_155035%3Ascalzafe_crab_LeonardoCristellaProvaPadStep3_0&subresource=getTransferStatus

where (after checking only one job, I admit) I see 4 files per job. One is likely the log that is not being tansferred, so 3 files per job .

Maybe the only "problem" here is that there are 3 output files but only 2 output datasets ?
It is not illegal to write multiple files in the same dataset.  But the destination dataset is not in transferdb.

**Comment by belforte** [comment]
I am also quite curious why one file xfer always fails... 
ALso I do not see those failures in the UI (see screenshot above)

**Comment by belforte** [comment]
I suggest to submit a small task (3 jobs e.g.) with same configuration so that we can easily check all things. I am getting convinced that server side everything is OK and rather there is possibly some confusion in how multiple datasets and thier outputs are managed in job wrapper vs. postjob etc.

**Comment by belforte** [comment]
Bottom line:
looks to me now that **everything** is fine.
But simply the one-line json which you reported in e.g. https://github.com/dmwm/CRABClient/issues/4814#issuecomment-529586342
is the summary of the publication status, not of the transfer status.
4 files are produced and properly transferred.
logs are not published by design
DQM are affected by this : https://github.com/dmwm/CRABServer/issues/5600#issuecomment-457372541

**Comment by lecriste** [comment]
I think so because a DQM dataset does not pass [this condition](https://github.com/dmwm/CRABServer/blob/4bcf667d40514cb0e2b42da07ddfb65119d5f759/src/python/TaskWorker/Actions/PostJob.py#L2364), therefore it is not added [here](https://github.com/dmwm/CRABServer/blob/4bcf667d40514cb0e2b42da07ddfb65119d5f759/src/python/TaskWorker/Actions/PostJob.py#L2374).

Shall we write a FAQ about "ignoring" the publication status reported by CRAB for tasks with a DQM output dataset or shall we try to account for a DQM dataset [here](https://github.com/dmwm/CRABServer/blob/4bcf667d40514cb0e2b42da07ddfb65119d5f759/src/python/TaskWorker/Actions/PostJob.py#L2620-L2626)?

**Comment by belforte** [comment]
sounds like you found the fix for #5600 !!!
worth giving it a try !

> try to account for a DQM dataset https://github.com/dmwm/CRABServer/blob/4bcf667d40514cb0e2b42da07ddfb65119d5f759/src/python/TaskWorker/Actions/PostJob.py#L2620-L2626 ?

I think we can give up on publishing generic ntuples and leave that for Rucio, but fixing DQM and nanoAOD could be easy if they have a well defined file_type.

**Comment by belforte** [comment]
will you try this, or should I ? I'd like to have a config then (with only 2 or 3 short jobs).

**Comment by lecriste** [comment]
I will try.
 
> I think we can give up on publishing generic ntuples and leave that for Rucio, but fixing DQM and nanoAOD could be easy if they have a well defined file_type.

Do they? I thought of adding 'DQM' as `filetype` for a "DQMRootOutputModule", no idea for nanoAOD (aren't they 'EDM' too?).

**Comment by belforte** [comment]
nanoAOD are not EDM.

**Comment by belforte** [comment]
but I am not sure that there is a reliable way to tell that a job produce nanoAOD format. The information will not be in the user PSet, but only in the FJR.

**Comment by belforte** [comment]
nanoAOD are produced by NanoAODOutputModule instead of PoolOutputModule.
Although they have a switch to allow users to override this and pretend nanoAOD are normal EDM, so that CRAB will publish:
https://github.com/cms-sw/cmssw/blob/eabd171a112ba4f38557f8d2efbf96968517550a/PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc#L250

**Comment by lecriste** [comment]
@belforte [this](https://github.com/lecriste/CRABServer/commit/b68f0f3b7178546933568323c08010c66da8b841) should set the correct value for `tm_output_dataset` also in case of a DQM dataset.

By changing the code I noticed these two lines:
https://github.com/dmwm/CRABServer/blob/4bcf667d40514cb0e2b42da07ddfb65119d5f759/src/python/TaskWorker/Actions/PostJob.py#L2617-L2618

do they make sense for you? I would expect the second line to be placed after the [last edit](https://github.com/dmwm/CRABServer/blob/4bcf667d40514cb0e2b42da07ddfb65119d5f759/src/python/TaskWorker/Actions/PostJob.py#L2657) of `file_info`.

**Comment by lecriste** [comment]
Closed via https://github.com/dmwm/CRABServer/pull/5944
