### ISSUE TITLE
refine CMSSW config caching

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4826]
with ref to #4824 finalize the plan as agreed in
https://github.com/dmwm/CRABClient/pull/4824#issuecomment-528646511
in particular document the design in the code

**Comment by belforte** [comment]
I tested that above commit does not break plain submission and passes the test from @cbbrainerd for allowing multiple submissions w/o loading CMSSW config twice : https://github.com/dmwm/CRABClient/pull/4824#issuecomment-528336773

**Comment by cbbrainerd** [comment]
@belforte It looks fine to me as well.

**Comment by belforte** [comment]
thanks @cbbrainerd , I changed a bit in order to make sure that it also catches changes in config file, config file arguments or sys.path .
