### ISSUE TITLE
make crab checkwrite work with Rucio endpoints

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4845]
seems that latest client was build w/o the latest ServerUtilities.py from server
we need to review the procedure.
```
belforte@lxplus729/TC3> crab --version
CRAB client v3.3.1910.patch2

belforte@lxplus729/TC3> crab checkwrite --site=T2_CH_CERN --lfn=/store/test/rucio/int/user/belforte/myfirstRucioTest
Validating LFN /store/test/rucio/int/user/belforte/myfirstRucioTest...
Refusing to check write permission in /store/test/rucio/int/user/belforte/myfirstRucioTest, because this is not an allowed LFN for stageout.
The LFN must start with either '/store/user/<username>/' or '/store/group/<groupname>/' (or '/store/local/<something>/' if publication is off), where username is your username as registered in CMS (i.e. the username of your CERN primary account).
LFN /store/test/rucio/int/user/belforte/myfirstRucioTest is not valid.
belforte@lxplus729/TC3> 


```

**Comment by belforte** [comment]
also these lines need to be changed, since they would call `checkOutLFN` without `username` being defined
https://github.com/dmwm/CRABClient/blob/b7522184dc4a23c3708c3ce046b3fc0f8c1eaf52/src/python/CRABClient/Commands/checkwrite.py#L55-L59
all in all code would be cleaner if username is always defined and filled.

**Comment by dciangot** [comment]
I'm not sure to understand this. 
@belforte What are you suggesting to do?

**Comment by belforte** [comment]
Change the lfn check to accept rucio endpointssent from Stefano's mobileOn Nov 4, 2019 02:02, dciangot <notifications@github.com> wrote:I'm not sure to understand this.
@belforte What are you suggesting to do?

**Comment by lecriste** [comment]
> seems that latest client was build w/o the latest ServerUtilities.py from server

Right, I did not update this line:
https://github.com/lecriste/cmsdist/blob/f15a31de28655ac3de01d533b8a3373e1f98bb7e/crabclient.spec#L9

> we need to review the procedure.

It's all about that `crabserver` tag in the `crabclient.spec` file, right?

**Comment by belforte** [comment]
That is surely needed. I also believe that the username thing should be done. But the best way is to test. I do not know more than you do (and likely less) about how Crab client is built.

**Comment by belforte** [comment]
I am having second thoughts. Only production proxy can write in Rucio directory. User proxy will always fails. So this test becomes useless. I'd start with only printing a proper message. Later on we can see if using this to check that user is enable in Rucio for that site. It is still good to make sure that output can be saved, before running zilions of jobs. We will also need to change the check done in the TaskWorker. Again the only sensible check may that the user is enabled and has quota at the target site.
@dciangot please review this, and write down a correct action list, preferrably as a couple of GIT issues (One per server, one per client). Even better if followed by a PR, but I guess I can do the coding if you tell me what's needed and how to do.

**Comment by dciangot** [comment]
#4849 #4848 
I think these two should be ok, covering most of the cases.

**Comment by belforte** [comment]
this was long done by @dciangot as per https://github.com/dmwm/CRABClient/issues/4845#issuecomment-550340098
will open new issued if/as needed when testing Rucio more
