### ISSUE TITLE
port to WMCore 1.2.8  / CRAB 3.3.1812.rc3

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4855]
See
https://github.com/dmwm/CRABServer/issues/5984#issuecomment-553663518

requires to syncronize change to WMCore version (for `pycurl_manager`) and CRAB Server version (for `RESTInteractions.py`) in building the new client.

**Comment by belforte** [comment]
@lecriste, AFAICT crabclient is now build with WMCore 1.2.8, so this was done.
Do you confirm, can we close ?
thanks.

**Comment by lecriste** [comment]
Yes, since this version:
https://github.com/cms-sw/cmsdist/pull/5396/files
