### ISSUE TITLE
TypeError in purge command: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABClient#4864]
`tm_schedd` can be not set [here](https://github.com/dmwm/CRABClient/blob/c25551a3dfcca59b30743d431271204b64867915/src/python/CRABClient/Commands/purge.py#L35) and so `scheddaddress` would not contain any '@'.
Probably we need to check the task status [beforehand](https://github.com/dmwm/CRABClient/blob/c25551a3dfcca59b30743d431271204b64867915/src/python/CRABClient/Commands/purge.py#L36).

**Comment by belforte** [comment]
this `scheddaddress` is only used to do gsissh to the schedd to remove the task webdir. Which is the only reason why we run gsissh server on schedd's, which is a security risk
I\d rather take it as a good thing that it has been broken for a while w/o any problem, call it a feature, and remove the code and the mention of the possibility. We have made progresses over time in keeping logs side under control and there seems to be no need to be more aggressive than the current disk cleanup policy. In case we could review that policy, i.e. leave logs around for a shorter time for a killed task.

**Comment by lecriste** [comment]
> I\d rather take it as a good thing that it has been broken for a while w/o any problem, call it a feature, and remove the code and the mention of the possibility.

@belforte, I'm not sure I understand what you mean with `remove the code and the mention of the possibility`.
Anyhow I just want to protect the code from that exception:
https://github.com/dmwm/CRABClient/pull/4865/files

**Comment by belforte** [comment]
I meant to deprecate the possibility for crab purge to remove files on schedd. Removing the code here, the documentation, the option in the command etc.

I thought that you meant that the code always fail now. Maybe I misunderstood. What exactly will change ? Will it start to work or simply replace one more well named exception for an obscure one ?

I am confused as to what exactly you want to do here.

**Comment by lecriste** [comment]
> I meant to deprecate the possibility for crab purge to remove files on schedd. Removing the code here, the documentation, the option in the command etc.

Ok, so you mean to remove these lines:
https://github.com/dmwm/CRABClient/blob/ebd5d8c1b2188cf84cf8052cf0c5245e0426f04c/src/python/CRABClient/Commands/purge.py#L79-L103


> I thought that you meant that the code always fail now. Maybe I misunderstood.

It fails when `crab purge` is issued for a task in a state different from
https://github.com/dmwm/CRABClient/blob/ebd5d8c1b2188cf84cf8052cf0c5245e0426f04c/src/python/CRABClient/Commands/purge.py#L46

but before the exception with the proper message can be raised:
https://github.com/dmwm/CRABClient/blob/ebd5d8c1b2188cf84cf8052cf0c5245e0426f04c/src/python/CRABClient/Commands/purge.py#L49


> What exactly will change ? Will it start to work or simply replace one more well named exception for an obscure one ?

With [this change](https://github.com/dmwm/CRABClient/pull/4865/files) the expected exception will be raised, instead of `TypeError`.

> I am confused as to what exactly you want to do here.

Shall I also remove [those gssish lines](https://github.com/dmwm/CRABClient/blob/ebd5d8c1b2188cf84cf8052cf0c5245e0426f04c/src/python/CRABClient/Commands/purge.py#L79-L103
)?

**Comment by belforte** [comment]
I see.
But basically the state selection forbids to purge running tasks, which makes sense, things should be stopped first. But then shouldn't the exception be something like 'kill the task before purging' rather than 'schedd address not found' ? The latter does not help nor the user nor the expert to figure out what's going on. 
Is this a very rare error ?

Anyhow, do not remove those gsissh lines for the time being. I'd rather start by be changing the purge command to enforce the `--cache` option.

**Comment by belforte** [comment]
maybe it is enough to move the lines checking the schedd address to after the status check ?
Though I do not understand why schedd can not be determined for a running task.

Myabe the error that you indicate can only happen in case of SUBMITFAILED ? If nothing was sent to schedd it would make sense to simply clean cache and return success.

**Comment by belforte** [comment]
do you have an example of this error ?

**Comment by lecriste** [comment]
> maybe it is enough to move the lines checking the schedd address to after the status check ?

Yes, I was about to propose that.

> Though I do not understand why schedd can not be determined for a running task.

Indeed it can not happen. I got this error for a task in status NEW.
 
> Myabe the error that you indicate can only happen in case of SUBMITFAILED ? If nothing was sent to schedd it would make sense to simply clean cache and return success.

Ok, will do.

**Comment by belforte** [comment]
OK. still worth cleaning the usercache though
