### ISSUE TITLE
make command completion work also for crab-prod/pre/dev

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4866]
see
https://github.com/dmwm/CRABClient/issues/4844#issuecomment-574772814

need to change
**https://github.com/dmwm/CRABClient/blob/d41695646c20936a4d5671f2abd566ea91a7ac13/etc/crab-bash-completion.sh#L284**

**Comment by smuzaffar** [comment]
@belforte , no need to change the CRABClient/etc/crab-bash-completion.sh in the repository. We can fix this at the build time. As we build three different packages crab-prod, crab-pre and crab-dev, so each one of these can just register a different function e.g.
complete -F _UseCrabpre -o filenames crab-pre
complete -F _UseCrabprod -o filenames crab-prod
complete -F _UseCrabdev -o filenames crab-dev

I have tested this and works fine.

**Comment by belforte** [comment]
I see. Should we  then remove that list from crab-bash-completion.sh, leaving it only as a a file which defines the autocompletion function and maybe only have a comment explaining to future maintainers of the Client that this scritp will be used as you write in the build process ?

**Comment by smuzaffar** [comment]
yes please remove the extra crab-* list from crab-bash-completion.sh. Just revert your last change. It will allow you to source it locally (for local development) to test new options.

**Comment by belforte** [comment]
Done. I guess I better not touch anything until I hear from you.
