### ISSUE TITLE
Random time range applied automatically by Grafana

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABClient#4882]
Based on
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5536/1/1/1/1/2/2.html

we should add `&from=now-2M&to=now` at the end of
https://github.com/dmwm/CRABClient/blob/eaffb9934c4d44275b4a9dc9167de4515dd40b42/src/python/CRABClient/Commands/status.py#L354

Bonus point if `2M` is replaced with a function of [TASKLIFETIME](https://github.com/dmwm/CRABServer/blob/4dd075c38158cd50ccfe8616af38e161bda24de4/src/python/ServerUtilities.py#L47)

**Comment by belforte** [comment]
thanks for spotting the Grafana bug Leo.
TASKLIFTME Is hardcoded to 30 days in CrabServer/ServerUtilities. I do not thing it will ever change. But if you can explain the rational for 2M instead of 1M I can try think of something,
maybe the time range could be basted on the task time stamp (submission time) ? I am not sure what the current URL will show for a 2 or 3 month old task. IIRB this is from  data in InfluxDB and hence we have full history. @cronosnull  what do you think ?

**Comment by belforte** [comment]
@ddaina the ptyhon part is trivial, but there's some "what exactly to do" which I do not think you should try to sort out by yourself yet. I will take care of this issue.

**Comment by cronosnull** [comment]
Hi @belforte,

This data is in a special ElasticSearch index which has a subset of the data for a little longer than the main condor one (up to 3 months, but based on the task creation date and only the fields we use in the dashboards).

IIRC, the original plan was to use the task creation time as the "from" value and `now` as the `to` value, but it is easier and has the same practical effects to use a fixed `from` long enough to be used in all the tasks (I was thinking in 3 months, as a safe bet, but as the task life is only one month maybe 30 days is enough).

In this index the document id is the global job id, so the dashboard will show always the last report we have for each job.

**Comment by belforte** [comment]
thanks @cronosnull we willl put in a time range like taskcreation + 40 days. Can the end of the range be harmellsy in the future ? otherwise we will have to put NOW. Where is it documented for the confused user that tasks older than 3 months are not visible in there ?

**Comment by cronosnull** [comment]
I just added a line about that in the instructions panel. (also I fixed the pie charts, I noticed the query for pending wasn't working as expected)

**Comment by belforte** [comment]
thanks. what abut the `to` value in the future ?

**Comment by belforte** [comment]
anyhow my conclusion so far is that we should use `from taskcreation date to now`

**Comment by cronosnull** [comment]
Yes, future dates are ok, but it will have the same behavior than use `now`.

**Comment by belforte** [comment]
with the new code crab status prints something like
```
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=belforte&var-task=200208_153851%3Abelforte_crab_20200208_163847&from=1581176331000&to=now
```

**Comment by belforte** [comment]
now in new tag 3.3.2002.rc4.
should appear in crab-dev in IB : https://github.com/cms-sw/cmsdist/pull/5560
