### ISSUE TITLE
replace import httplib

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4923]
for python3 compatibility, replace
```
from httplib import HTTPExceptions
``` 
with
```
from http.client import HTTPExceptions
```

**Comment by cbbrainerd** [comment]
@belforte This seems to break compatibility with older versions of python (The version 2.7.11 used in 8_0_X, at least), which gives the error 

```
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200719.00/bin/crab", line 25, in <module>
    from http.client import HTTPException
ImportError: No module named http.client
```

Is this intended? You could probably replace it with

```
try:
    from http.client import HTTPExceptions
except ImportError:
    from httplib import HTTPExceptions
```

without any real performance implications. Or add another python file that does this import and just import from there everywhere else it appears in the code.
