### ISSUE TITLE
Fix pylint errors - CRABClient

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABClient#4930]
List of pylint errors for CRABClient:

- [x] Module CRABClient.Commands.report:
E:436,22: Unsupported format character ' ' (0x20) at index 25 (bad-format-character)
E:436,75: Undefined variable 'exitcode' (undefined-variable)
E:458,22: Unsupported format character ' ' (0x20) at index 25 (bad-format-character)
E:458,75: Undefined variable 'exitcode' (undefined-variable)

**Comment by ddaina** [comment]
Other warnings that should be fixed:
Module CRABClient.JobType.Analysis:
W:  8, 0: Uses of a deprecated module 'string' (deprecated-module)

Module CRABClient.JobType.CopyCat:
W:  9, 0: Uses of a deprecated module 'string' (deprecated-module)

Module CRABClient.ClientUtilities:
W: 18, 0: Uses of a deprecated module 'string' (deprecated-module)

Module CRABClient.Commands.submit:
W: 14, 0: Uses of a deprecated module 'string' (deprecated-module)

Module CRABClient.Commands.preparelocal:
W: 32, 8: Expression "(os.path.isdir(self.options.destdir)) or (os.makedirs(self.options.destdir))" is assigned to nothing (expression-not-assigned)

Module CRABClient.Commands.SubCommand
R:412,11: Comparison to literal (literal-comparison)

**Comment by ddaina** [comment]
@belforte regarding warning in Module CRABClient.Commands.preparelocal - should I change this:
https://github.com/dmwm/CRABClient/blob/87d6aee7ca65f90858549f81790b28655d2c4ef4/src/python/CRABClient/Commands/preparelocal.py#L32

to this:
```
if not os.path.isdir(self.options.destdir):
    os.makedirs(self.options.destdir)
```
?

**Comment by belforte** [comment]
yes that seems what the original developer had in mind. I agree that the bash-like syntax is not good. Better not rely on a specific order in which the parts of the OR statement are processed.
I was not expecting you to go and fix all pylint warnings, but that's a different story.

**Comment by belforte** [comment]
looks like we forgot to close
