### ISSUE TITLE
List (and limit) dependencies from WMCore

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4940]
in view of migration to python3 https://github.com/dmwm/CRABClient/issues/4925
it is important to know exactly which WMCore modules does CRABClient depend on,
since those may need special treatment in order to work also with older CMSSW versions
which do not have py2-future library.

**Comment by belforte** [comment]
References about python3 migration of WMCore and https calls which may affect CRAB

#4936 
https://github.com/dmwm/WMCore/issues/9834

a longish discussion is in this PR: https://github.com/dmwm/WMCore/pull/9762 
in particular following:
https://github.com/dmwm/WMCore/pull/9762#issuecomment-672939985

**Comment by belforte** [comment]
* via CRABServer/RESTInteractions.py
  * from WMCore.Services.Requests import JSONRequests
  * from WMCore.Services.pycurl_manager import RequestHandler
* via CRABServer/ServerUtilities.py
  *   from WMCore.Services.PhEDEx.PhEDEx import PhEDEx
  *   from WMCore.WMExceptions import STAGEOUT_ERRORS

* from code in CRABCkient/src/python
```
LapSB:CRABClient$ 
LapSB:CRABClient$ pyfind WMCore|grep import|sort|uniq
from WMCore.Configuration import Configuration
from WMCore.Configuration import Configuration, saveConfigurationFile
from WMCore.Configuration import loadConfigurationFile, Configuration
from WMCore.Credential.Proxy import Proxy, CredentialException
from WMCore.DataStructs.LumiList import LumiList
from WMCore.Lexicon import jobrange
from WMCore.Services.PhEDEx.PhEDEx import PhEDEx
from WMCore.Services.pycurl_manager import RequestHandler
from WMCore.Services.UserFileCache.UserFileCache import UserFileCache
from WMCore.Services.UserFileCache.UserFileCache  import UserFileCache
from WMCore.WebTools.RESTModel import RESTModel
import WMCore
LapSB:
```

the `import WMCore` is in a test module, and can be replaces with `import WMCore.Lexicon`

PhEDEx will go way, and replaced by Rucio

**Comment by belforte** [comment]
so from the above I will summarize WMCore dependencies as
1. things which I presume/hope will not have any py/3 issue:
 1.1. WMCore.Lexicon 
 1.2. WMCore.Configuration
 1.3. WMCore.DataStructs.LumiList
 1.4. WMCore.WMExceptions
2. things used only by CRAB
 2.1.  WMCore.Services.UserFileCache   which depends on WMCore.Services.Service
3. a class common to CRAB and WMA, but we use disjoint sets of methods. Could even split.
 3.1. WMCore.Credential.Proxy
4. The HTTPS stuff which is always the sticky point
  4.1 WMCore.Services.pycurl_manager
5. Rucio stuff, which is new, but I suspect relies on the above `pycurl_manager`
  5.1. Details to be see, there's no call to Rucio in current CRAB Client

I think that of all those, only 4. imports from future, i.e. should be the only class requiring py2-future.

**Comment by amaltaro** [comment]
Stefano, from the list above, I believe only:
 2.1. WMCore.Services.UserFileCache which depends on WMCore.Services.Service
hasn't been modernized yet.

@mapellidario  Dario, AFAIK this UserFleCache is only used by CRAB. In this case, do you think we could modernize that package next? Such that Stefano can give it a try?

@belforte Stefano, I still think it would be better if CRAB waited until March (or April) to start this migration. We are modernizing and validating things as we can, but sometimes a bug manages to go in.

**Comment by belforte** [comment]
I am in no special hurry to migrate to py3. No worry. Danilo was pushing, but that's easy to deal with.
On the "summer" time scale I would actually like to get rid or CRABCache service and dependency from UserFileCache !

Let's come back to this in a couple days once I have some overall view of what py3 for CRAB implies.

**Comment by mapellidario** [comment]
`WMCore.Services.UserFileCache` is in [slice 5](https://github.com/dmwm/WMCore/issues/10116), which is the next one in our schedule! I can start it tomorrow. 
However, `WMCore.Configuration` is [on hold](https://github.com/dmwm/WMCore/issues/9973). We decided to postpone it until we had a py3 environment, since it is almost impossible to properly handle types that have been updated in py3 without any testing

**Comment by belforte** [comment]
@mapellidario as I wrote. I'd rather stop using that. Is CRAB the only customer for the UserFileCache ?

**Comment by amaltaro** [comment]
> Is CRAB the only customer for the UserFileCache ?

Yes!

**Comment by belforte** [comment]
I will leave this issue open, but am going to open separate ones about each topic. Or maybe will turn into a GH project.

**Comment by belforte** [comment]
List is Done ! Items are tracked in the ad-hoc project https://github.com/dmwm/CRABClient/projects/2
