### ISSUE TITLE
tell user how maby jobs were created by splitting in dryrun case.

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5065]
see https://github.com/dmwm/CRABClient/issues/5064#issuecomment-900282373

One possibility may be to use uploadMessage from server to add a message to the task
with the number of jobs created by splitter. But I do no know if that's available in any 
place. Both Splitter and DagmanCreator run before dryRunUploader, but I do not find
the number of created jobs in their log. Anyhow this would be a crab server issue.

**Comment by belforte** [comment]
On Hold since there may be a solution server-side via https://github.com/dmwm/CRABServer/issues/6713

**Comment by belforte** [comment]
maybe as simple as logging to console the content of `splitting-summary.json` here
https://github.com/dmwm/CRABClient/blob/e30eb13720d16cc4831c54ade6bf331e7a2e6353/src/python/CRABClient/Commands/submit.py#L394-L395

**Comment by belforte** [comment]
@simonepigazzini will something like the following do ?
(that's bare `pprint.pprint()` output, I can prettify it a bit more)
but please not that this line was there already:
`Task consists of 3312 jobs to process 993369 events`
was it not what you were looking for ?

```
belforte@lxplus741/TC3> crab submit --dryrun 
Will use CRAB configuration file crabConfig.py
Importing CMSSW configuration demoanalyzer.py
Finished importing CMSSW configuration demoanalyzer.py
Sending the request to the server at cmsweb.cern.ch
Success: Your task has been delivered to the prod CRAB3 server.
Task name: 210817_153931:belforte_crab_20210817_173923
Project dir: ./crab_20210817_173923
Waiting for task to be processed
Checking task status
Task status: NEW
Please wait...
Task status: QUEUED
Please wait...
Task status: UPLOADED

Created temporary directory for dry run sandbox in /tmp/belforte/tmp1M9m3M
{u'algo': u'EventAwareLumiBased',
 u'avg_events': 299.9302536231884,
 u'avg_lumis': 1.0,
 u'max_events': 300.0,
 u'max_lumis': 1,
 u'min_events': 297.0,
 u'min_lumis': 1,
 u'total_events': 993369.0,
 u'total_jobs': 3312,
 u'total_lumis': 3312}
Executing test, please wait...

Using EventAwareLumiBased splitting
Task consists of 3312 jobs to process 993369 events
The longest job will process 300 events, with an estimated processing time of 1 minutes
The average job will process 299 events, with an estimated processing time of 1 minutes
The shortest job will process 297 events, with an estimated processing time of 1 minutes
The estimated memory requirement is 763 MB

Timing quantities given below are ESTIMATES. Keep in mind that external factors
such as transient file-access delays can reduce estimate reliability.

For ~480 minute jobs, use:
Data.unitsPerJob = 99549
You will need to submit a new task
Data.totalUnits = 993369

Dry run requested: task paused
To continue processing, use 'crab proceed'

Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20210817_173923/crab.log
belforte@lxplus741/TC3> 

```

**Comment by simonepigazzini** [comment]
Ciao,

precisely, I'm aware of this and it works nicely. What I meant is that when using the CRABClient one could in principle be able to get this information from the client w/o having to parse the stdout. This would require to make some of the information printed above member variables of the submit class:

https://gitlab.cern.ch/spigazzi/PhiSym/-/blob/automation_dev/EcalCalibAlgos/scripts/phisym_crab_submit.py#L56

https://gitlab.cern.ch/spigazzi/PhiSym/-/blob/automation_dev/EcalCalibAlgos/scripts/phisym_crab_submit.py#L63

**Comment by belforte** [comment]
OK.  I understand now. Thanks,
I will open an ad hoc issue and see what I can do.

**Comment by belforte** [comment]
requst should now be captured in https://github.com/dmwm/CRABClient/issues/5066
and there is no need for any server-side change
