### ISSUE TITLE
ignore 1xx status responses

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABClient#5072]
> A client MUST be prepared to accept one or more 1xx status responses prior to a regular response, even if the client does not expect a 100 (Continue) status message. Unexpected 1xx status responses MAY be ignored by a user agent.

from https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

code in 
https://github.com/dmwm/CRABClient/blob/6bd1c043c8acaf7c1773984732286f0628dd9cd3/src/python/CRABClient/CrabRestInterface.py#L144-#L153 
and 
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/CrabRestInterface.py#L162
fails to ignore 1xx status response and makes task submissions to fail by getting incorrect HTTP code.

**Comment by belforte** [comment]
technical note:
here CRAB code is not an HTTP client.
The client is `curl` and it is surely behaving correctly and possibly requesting/expecting the 100 (Continue) message.
 But we need to be correct in interpreting curl log.
