### ISSUE TITLE
realpath command not found on cc6

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABClient#5106]
trying to execute following line on SLC6
https://github.com/dmwm/CRABClient/blob/81edeba196f6a49143388bcb182b62421065412f/bin/crab#L3
results in 
```
Singularity> source private/WORK/SETUP-LOCAL
/afs/cern.ch/user/d/ddirmait
/afs/cern.ch/user/d/ddirmait/git/CRABClient/bin/crab: line 3: realpath: command not found
dirname: missing operand
Try `dirname --help' for more information.
```

**Comment by belforte** [comment]
:-(

**Comment by belforte** [comment]
I fear that w/o using `realpath` there can be a problem with following symbolic links.
It is difficult to make tests in /cvmfs, of course.

**Comment by belforte** [comment]
yet, there is some evidence that this syntax works everywhere from `/cvmfs/cms.cern.ch/common/crab`
```
crab_pkg=$(basename $0)
```
so it may simply be that I gave a bad advice :-)
