### ISSUE TITLE
make CMSSWConfig find output files also in FinalPath

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5160]
so far CRAB automatically finds EDM output files in output module `PoolOutputModule` defined as `cms.EndPath`, but now there's also the possibility to define output as `cms.FinalPath`.
See: https://github.com/cms-sw/cmssw/issues/37301
and in particular
https://github.com/cms-sw/cmssw/issues/37301#issuecomment-1075536022

**Comment by belforte** [comment]
for my use,  here's a way to test Matti's fix
```
belforte@lxplus715/TestConfig> env|grep CRAB_CMS
belforte@lxplus715/TestConfig> cd ..
belforte@lxplus715/TC3> python3
cfgPython 3.6.4 (default, Apr 19 2019, 15:54:05) 
[GCC 7.4.1 20190129] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> userConfig='minimalPS.py'
>>> import os
>>> cfgBaseName = os.path.basename(userConfig).replace(".py", "")
>>> cfgBaseName
'minimalPS'
>>> cfgDirName = os.path.dirname(os.path.abspath(userConfig))
>>> cfgDirName
'/afs/cern.ch/work/b/belforte/CRAB3/TC3'
>>> import imp
>>> configFile, pathname, description = imp.find_module(cfgBaseName, [cfgDirName])
>>> configFile 
<_io.TextIOWrapper name='/afs/cern.ch/work/b/belforte/CRAB3/TC3/minimalPS.py' mode='r' encoding='utf-8'>
>>> pathname 
'/afs/cern.ch/work/b/belforte/CRAB3/TC3/minimalPS.py'
>>> description
('.py', 'r', 1)
>>> fullConfig = imp.load_module(cfgBaseName, configFile, pathname, description)
>>> process=fullConfig.process
>>> for m in process.endpaths_().itervalues():
...   print(m)
... 
output
>>> hasattr(process, "finalpaths_") 
False
>>> 

```
Now waiting for an example PSet with FinalPath and then will make a PR. See 
https://github.com/cms-sw/cmssw/issues/37301#issuecomment-1075631870

**Comment by sarafiorendi** [comment]
hi Stefano, 
you can find an example cfg in this folder
`/afs/cern.ch/user/f/fiorendi/public/forCrab/
`
the pSet where the FinalPath is defined is  
`/afs/cern.ch/user/f/fiorendi/public/forCrab/customise_forStefano.py
`
and imports
`/afs/cern.ch/user/f/fiorendi/public/forCrab/hlt_doubleDisplTau.py
`
let me know if you need anything else or if you want me to test the changes.

**Comment by belforte** [comment]
thanks @sarafiorendi , I can reproduce the problem, I think I do not need anything else.

**Comment by belforte** [comment]
this fix is in new tag https://github.com/dmwm/CRABClient/releases/tag/v3.220323
which should be available in CMSSW IntegrationBuild tomorrow as `crab-dev` [1]
and move to default CVMFS when a new CMSSW_12_4 is built
It will move to `crab-prod` after it was tested more as `crab-dev`

[1]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSCrabClient#Using_CRABClient_from_nightly_CM

**Comment by belforte** [comment]
@sarafiorendi the fix is now available in the IntegrationBuild as `crab-dev` you can use it via [1] above, or  ore explicitly:
```
source /cvmfs/cms-ib.cern.ch/latest/cmsset_default.sh
cd <your favourite scram directory>
cmsenv
source /cvmfs/cms-ib.cern.ch/latest/common/crab-setup.sh dev
alias crab='crab-dev'
```
I will appreciate if you can let me know if things work for you now (expecially in case they still don't !)

**Comment by sarafiorendi** [comment]
hi @belforte,
I just tried and it worked, no warning messages and the output file is there.
thanks for the fix!
