### ISSUE TITLE
add support for usePartialDataset (quick hack)

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5163]
with ref. to https://github.com/dmwm/CRABServer/issues/7135
client should support a new configuration parameter, e.g. `useParialDataset` or `useAvailableData` or `skipTapeRecall` ... best name still to be defined.

This could be done in two steps.

1. do it using current hack : `config.Data.runRange = ‘0’` which only requires changes in the Client.
  * and add to documentation 
  * and make sure in Client that user does not set runRange, refuse to submit in case
2. add a new parameter to the DB Task table and do it the same way as any other config. parameter, so allow `runRange` to be used normally 
  * this step will be transparent to users and could be for a new GH issue

**Comment by belforte** [comment]
@novicecpp shall we close this ?

**Comment by novicecpp** [comment]
Sure. I am closing..
