### ISSUE TITLE
add $CMSSW_BASE/config/SCRAM/hooks to the sandbox

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5196]
see https://cms-talk.web.cern.ch/t/sandbox-questions/24063/3

- [x] change the code
- [x] update documentation : https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#What_are_the_files_CRAB_adds_to

**Comment by kpedro88** [comment]
Just to be completely accurate, the directory name is `$CMSSW_BASE/config/SCRAM/hooks` (plural hooks).

Also, some older versions of CMSSW will not have this directory by default. This is expected, so the sandboxing code should just move on if it can't find the directory.

**Comment by belforte** [comment]
@smuzaffar I presume that this OK with you as well and that there can not be any adverse effect. In case.. let me know.

**Comment by smuzaffar** [comment]
@belforte , yes this is fine.

**Comment by belforte** [comment]
@kpedro88 the dev version of CRABClient now in Integration Build now has the fix for this and for venv subdirectory #5197 .
I tested the change, but will nevertheless very much appreciate if you give it a try too and confirm that solves your need. If there's something to change or add, better to do it before it goes to mainstream production as the time to push changes there is O(1 month).

Please let me know. Thanks

You can use the new version with
```bash
source /cvmfs/cms-ib.cern.ch/latest/cmsset_default.sh
crab-dev ...
```

(see also [twiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSCrabClient#Using_CRABClient_from_nightly_CM) )

**Comment by kpedro88** [comment]
@belforte thanks, everything appears to work in my latest test! I'll update the [cms-sw.github.io](http://cms-sw.github.io/) docs now.

**Comment by belforte** [comment]
thanks Kevin. Please note that now `crab-dev` in the main CVMFS has been updated, no need to use `cms-ib`
