### ISSUE TITLE
allow a user to add their own tarfile to the sandox

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#5198]
i.e. make sure that such tar is expanded on the WN
e,g. look for files whose name contains `.tar.` or ends with `.tar` or `.tgz` or `.tbz`

see https://cms-talk.web.cern.ch/t/sandbox-questions/24063/2

**Comment by kpedro88** [comment]
A thought: some people name their tar files as `.tgz`, so probably check for that one, too.

**Comment by belforte** [comment]
there is nothing to change in Client, this is simply a matter of calling `tar` in the job wrapper. Will open issue in crabserver repo
