### ISSUE TITLE
Block publishing a new CRABClient until v3.240322

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABClient#5294]
Subtask of https://github.com/dmwm/CRABClient/issues/5289.

This is due to a break change introduced in https://github.com/dmwm/CRABClient/pull/5287.
The change on the server side [was deployed on 2024-02-20](https://cms-talk.web.cern.ch/t/production-taskworker-updated/33636/2). We are waiting until the tasks submitted before 2024-02-20 expire. 

Deploy date: after 2024-03-22

**Comment by novicecpp** [comment]
Maybe we can update crabdev now?
I will do it after finish validation.

**Comment by belforte** [comment]
time to go.
- [ ] update crab-dev in IB to v3.240216 https://github.com/cms-sw/cmsdist/pull/9104
- [ ] validate crab-dev in IB
- [ ] move new v3.240216 to crab-prod in IB and current v3.240110 to crab-pre
- [ ] wait for change to be built in production /cvmfs (or trigger this by ourselves)

**Comment by belforte** [comment]
CRABClient v3.240416 is now default
```
belforte@lxplus803/TC3> which crab
/cvmfs/cms.cern.ch/common/crab
belforte@lxplus803/TC3> crab-prod --version
CRAB client v3.240416
```
